---
permalink: windows/concept-backing-up-and-restoring-files-using-br-tools.html 
sidebar: sidebar 
keywords: addition, back up, database, file, br, tool, restore, sap, system, storage 
summary: En plus de sauvegarder les fichiers de base de données, vous pouvez utiliser BR*Tools pour sauvegarder et restaurer tous les fichiers, tels que les fichiers système SAP stockés sur le système de stockage. 
---
= Sauvegarde et restauration de fichiers à l'aide de BR*Tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
En plus de sauvegarder les fichiers de base de données, vous pouvez utiliser BR*Tools pour sauvegarder et restaurer tous les fichiers, tels que les fichiers système SAP stockés sur le système de stockage.

Suivez la documentation SAP BR*Tools pour les commandes BRBACKUP et BRRESTORE. Les informations supplémentaires suivantes s'appliquent lorsque vous utilisez SnapManager pour SAP :

* Les fichiers doivent être stockés sur le système de stockage.
* Assurez-vous que vous disposez des autorisations nécessaires pour les fichiers que vous sauvegardez. Par exemple, la sauvegarde des fichiers système SAP (`BRBACKUP backup_mode=sap_dir`) Ou les fichiers système Oracle (`BRBACKUP backup_mode=ora_dir`) requiert l'autorisation root sur l'hôte. Utilisez le `su root` Commande avant d'exécuter BRBACKUP.

