---
permalink: windows/concept-managing-security-and-credentials.html 
sidebar: sidebar 
keywords: manage, security, snapmanager, apply, authentication, user, allow, resource, repository, repositories, host, profile, credential, management 
summary: 'Vous pouvez gérer la sécurité dans SnapManager en appliquant l"authentification des utilisateurs. La méthode d"authentification utilisateur vous permet d"accéder à des ressources telles que des référentiels, des hôtes et des profils.' 
---
= Sécurité et gestion des identifiants
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez gérer la sécurité dans SnapManager en appliquant l'authentification des utilisateurs. La méthode d'authentification utilisateur vous permet d'accéder à des ressources telles que des référentiels, des hôtes et des profils.

Lorsque vous effectuez une opération à l'aide de l'interface de ligne de commande ou de l'interface utilisateur graphique, SnapManager récupère les informations d'identification des référentiels et profils. SnapManager enregistre les informations d'identification des installations précédentes.

Le référentiel et les profils peuvent être sécurisés par un mot de passe. Un identifiant est le mot de passe configuré pour l'utilisateur pour un objet et le mot de passe n'est pas configuré sur l'objet lui-même.

Vous pouvez gérer l'authentification et les informations d'identification en effectuant les tâches suivantes :

* Gérez l'authentification des utilisateurs à l'aide d'invites de mot de passe lors des opérations ou à l'aide de `smsap credential set` commande.
+
Définissez les informations d'identification d'un référentiel, d'un hôte ou d'un profil.

* Affichez les informations d'identification qui régissent les ressources auxquelles vous avez accès.
* Effacez les informations d'identification d'un utilisateur pour toutes les ressources (hôtes, référentiels et profils).
* Supprimer les informations d'identification d'un utilisateur pour des ressources individuelles (hôtes, référentiels et profils).



NOTE: Si la base de données du référentiel se trouve sur un hôte Windows, l'utilisateur local ou administrateur et l'utilisateur du domaine doivent disposer des mêmes informations d'identification.
