---
permalink: windows/concept-managing-profiles-for-efficient-backups.html 
sidebar: sidebar 
keywords: create, profile, snapmanager, database, perform, operation, manage, efficient, backup 
summary: 'Vous devez créer un profil dans SnapManager pour la base de données sur laquelle vous souhaitez effectuer une opération. Vous devez sélectionner le profil, puis sélectionner l"opération que vous souhaitez effectuer.' 
---
= Gestion des profils pour des sauvegardes efficaces
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez créer un profil dans SnapManager pour la base de données sur laquelle vous souhaitez effectuer une opération. Vous devez sélectionner le profil, puis sélectionner l'opération que vous souhaitez effectuer.



== Tâches associées aux profils

Vous pouvez effectuer les tâches suivantes :

* Créez des profils pour activer les sauvegardes et les sauvegardes complètes ou partielles sur le stockage primaire ou secondaire.
+
Vous pouvez également créer des profils pour séparer les sauvegardes du journal d'archivage des sauvegardes du fichier de données.

* Vérifiez les profils.
* Mettre à jour les profils.
* Supprimer des profils.




== À propos des profils et de l'authentification

Lorsque vous créez un profil, vous pouvez spécifier une base de données et choisir l'une des méthodes suivantes pour vous connecter à la base de données :

* Authentification Oracle avec un nom d'utilisateur, un mot de passe et un port
* Authentification du système d'exploitation sans nom d'utilisateur, mot de passe ou port.
+
Pour l'authentification du système d'exploitation, vous devez entrer les informations d'utilisateur et de groupe du compte OS.

* Authentification de la base de données quand `sqlnet.authentication_services` Est défini sur *NONE*. SnapManager utilise ensuite le nom d'utilisateur et le mot de passe de la base de données pour toutes les connexions à la base de données cible. SnapManager peut également utiliser l'authentification native de Windows lorsque `sqlnet.authentication_services` Est défini sur *NTS*.


Vous pouvez définir `sqlnet.authentication_services` À *AUCUN* uniquement dans les environnements suivants :

|===
| Disposition de la base de données | Version Oracle | L'authentification de base de données est-elle prise en charge pour la base de données cible 


 a| 
Toute base de données non ASM et non RAC
 a| 
Oracle 10g et Oracle 11g (version inférieure à 11.2.0.3)
 a| 
Oui.

|===
[NOTE]
====
Après avoir désactivé cette option `sqlnet.authentication_services` et modifiez la méthode d'authentification pour l'authentification de la base de données, vous devez définir `sqlnet.authentication_services` À *AUCUN*.

====
Si vous accédez pour la première fois à un profil, vous devez saisir le mot de passe de votre profil. Une fois vos informations d'identification saisies, vous pouvez afficher les sauvegardes de la base de données dans le profil.
