---
permalink: windows/concept-profile-usage-for-br-tools-backups.html 
sidebar: sidebar 
keywords: br, tools, command, backint, interface, interface, snapmanager, profile, repository, credential, user, run, backup 
summary: 'Lorsque vous exécutez une commande BR*Tools qui utilise l"interface BACKINT, SnapManager utilise un profil du référentiel. Le référentiel est déterminé par les informations d"identification SnapManager de l"utilisateur exécutant la commande BR*Tools.' 
---
= Utilisation du profil pour les sauvegardes BR*Tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lorsque vous exécutez une commande BR*Tools qui utilise l'interface BACKINT, SnapManager utilise un profil du référentiel. Le référentiel est déterminé par les informations d'identification SnapManager de l'utilisateur exécutant la commande BR*Tools.

Par défaut, SnapManager utilise le profil portant le même nom que l'identificateur du système de base de données SAP.



== À propos de la création d'informations d'identification pour accéder au référentiel

Vous pouvez utiliser le `smsap credential set` Commande permettant de définir les informations d'identification du référentiel pour l'utilisateur BR*Tools.



== A propos de la spécification d'un autre nom de profil SnapManager

Tant que l'identifiant système est unique pour tous les hôtes dont les profils SnapManager se trouvent dans un référentiel donné, le nom de profil par défaut est suffisant. Vous pouvez créer le profil SnapManager et le nommer en utilisant la valeur d'identifiant du système de base de données.

Cependant, si le même identificateur système est utilisé sur des hôtes différents, ou si vous souhaitez spécifier plusieurs profils SnapManager à utiliser avec BR*Tools sur une instance SAP donnée, vous devez définir le nom du profil pour les commandes BR*Tools.

Les opérations de base de données planifiées au sein de l'application SAP s'exécutent en tant qu'utilisateur. Les opérations BR*Tools planifiées dans les applications SAP s'exécutent comme `SAPServiceSID`. Ces utilisateurs doivent avoir accès au référentiel et au profil.

L'utilisateur du service SAP SAPServiceSID ne permet pas à l'utilisateur de se connecter localement. Pour modifier cette règle, vous devez modifier la stratégie de sécurité locale en procédant comme suit :

.Étapes
. Cliquez sur *Démarrer* > *programmes* > *Outils d'administration* > *Stratégie de sécurité locale*.
. Développez *stratégies locales* et sélectionnez** attribution des droits utilisateur**
. Recherchez la stratégie *Deny log on local*.
. Cliquez avec le bouton droit de la souris et sélectionnez *Propriétés*.
. Supprimez *SAP Service User* dans cette liste.




== À propos de la création du fichier de paramètres de l'utilitaire de sauvegarde

La commande BR*Tools peut éventuellement passer un paramètre d'utilitaire de sauvegarde (`.utl` Parameter) file vers l'interface BACKINT. Par défaut, le nom de ce fichier est `initSID.utl`, Où SID est l'identifiant système de la base de données.

Par défaut, BR*Tools utilise le fichier de paramètres spécifié par `util_par_file` paramètre dans le `initSID.sap` fichier. Le fichier des paramètres de l'utilitaire de sauvegarde est normalement stocké dans le même répertoire que le `initSID.sap` fichier.

Autres `profile_name = <profile>` à la `.utl` fichier et enregistrement. Le profil est le nom du SnapManager _profile_ que vous souhaitez utiliser pour les commandes BR*Tools.

Le tableau suivant répertorie les paramètres supplémentaires de l'utilitaire de sauvegarde inclus dans le `.utl` fichier pour les opérations telles que la conservation des sauvegardes, la restauration rapide et la protection des données :

|===
| Exploitation | Paramètres de l'utilitaire de sauvegarde 


 a| 
La conservation des sauvegardes
 a| 
* Clé : conserver
* Valeur : illimitée




| horaire | tous les jours 


| hebdomadaire | tous les mois 
|===
Le tableau suivant décrit les différents paramètres de l'utilitaire de sauvegarde pour ces opérations :

|===
| Fonctionnement | Clé | Valeur 


 a| 
La conservation des sauvegardes
 a| 
rapide =
 a| 
secours

|===


== Ajout du paramètre de l'utilitaire de sauvegarde au fichier d'initialisation BR*Tools

SAP crée un fichier de profil de sauvegarde nommé `initSID.sap` Pour chaque instance de base de données SAP dans `$ORACLE_HOME\database\`. Vous pouvez utiliser ce fichier pour spécifier le paramètre de l'utilitaire de sauvegarde par défaut (`.utl`) Fichier utilisé pour les commandes BR*Tools.

.Étapes
. Modifiez le fichier initSID.sap et localisez la ligne commençant par `util_par_file =`.
. Annulez le commentaire de cette ligne et ajoutez le chemin d'accès au fichier de paramètres de l'utilitaire de sauvegarde qui contient le nom du profil, par exemple, `util_par_file = initSA1.utl`.
. Si vous spécifiez une valeur pour le `util_par_file`, assurez-vous que le fichier existe.
+
Si le fichier n'est pas trouvé, les commandes BRBACKUP échouent car elles tentent d'inclure ce fichier dans une sauvegarde.



Si l'une des conditions d'erreur suivantes est trouvée, vous devez utiliser le `-u` comme nom de profil :

* `Parameter files does not exist`
* `No profile_name entry`


Les deux `orasid` et `sidadm` Vous devez accéder au profil qui sera utilisé pour créer ou gérer les sauvegardes créées avec BR*Tools.



== Spécifier le nom du fichier de paramètres de l'utilitaire de sauvegarde dans la commande BR*Tools

Vous pouvez éventuellement spécifier le fichier des paramètres de l'utilitaire de sauvegarde (.utl parameter) dans les commandes BR*Tools à l'aide de l' `-r` option. La valeur de la ligne de commande remplace la valeur spécifiée dans le fichier d'initialisation SAP.

BR*Tools recherche le fichier de paramètres dans `$ORACLE_HOME\database\` répertoire. Si vous stockez le fichier à un autre emplacement, vous devez fournir le chemin complet avec le `-r` option. Par exemple :

`*brbackup -r C:\Oracle\NetApp_fcp_price_10g_enterprise_inst_vol1\database\initCER.utl ...*`
