---
permalink: windows/reference-the-smosmsapcredential-set-command.html 
sidebar: sidebar 
keywords: command, credential, user, access, secure, resource, host, repository, repositories, database, profile, password, snapmanager, option, smsap 
summary: 'Cette commande vous permet de définir les informations d"identification permettant aux utilisateurs d"accéder aux ressources sécurisées, telles que les hôtes, les référentiels et les profils de base de données. Le mot de passe hôte est le mot de passe de l’utilisateur sur l’hôte sur lequel SnapManager est exécuté. Le mot de passe du référentiel est le mot de passe de l"utilisateur Oracle qui contient le schéma du référentiel SnapManager. Le mot de passe du profil est un mot de passe composé par la personne qui crée le profil. Pour les options hôte et référentiel, si l"option -password facultative n"est pas incluse, vous serez invité à entrer un mot de passe du type spécifié dans les arguments de commande.' 
---
= La commande smsap Credential set
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cette commande vous permet de définir les informations d'identification permettant aux utilisateurs d'accéder aux ressources sécurisées, telles que les hôtes, les référentiels et les profils de base de données. Le mot de passe de l'hôte est le mot de passe de l'utilisateur sur l'hôte sur lequel SnapManager est exécuté. Le mot de passe du référentiel est le mot de passe de l'utilisateur Oracle qui contient le schéma du référentiel SnapManager. Le mot de passe du profil est un mot de passe composé par la personne qui crée le profil. Pour les options d'hôte et de référentiel, si l'option est disponible `-password` l'option n'est pas incluse, vous serez invité à saisir un mot de passe du type spécifié dans les arguments de commande.



== Syntaxe

[listing]
----

smsap credential set
[-host
-name host_name
-username username]
[-password password]] |
[-repository
-dbname repo_service_name
-host repo_host
-login -username repo_username] [-password repo_password]]
-port repo_port |
[-profile
-name profile_name]
[-password password]]
[-quiet | -verbose]
----


== Paramètres

* *`-host _hostname_`*
+
Spécifie le nom ou l'adresse IP du serveur hôte sur lequel SnapManager s'exécute.

+
Le `-host` le paramètre inclut les options suivantes :

+
** `-name host_name`: Indique le nom de l'hôte pour lequel vous allez définir le mot de passe.
** `-username user_name`: Indique le nom d'utilisateur sur l'hôte.
** `-password password`: Spécifie le mot de passe de l'utilisateur sur l'hôte.


* *`-repository -dbname`*
+
Indique le nom de la base de données qui stocke le profil. Utilisez le nom global ou le SID.

+
Le `-repository` le paramètre inclut les options suivantes :

+
** `-dbnamerepo_service_name`: Indique le nom de la base de données qui stocke le profil. Utilisez le nom global ou le SID.
** `-host repo_host`: Indique le nom ou l'adresse IP du serveur hôte sur lequel s'exécute la base de données de référentiel.
** `-login-username repo_username`: Indique le nom d'utilisateur nécessaire pour accéder à la base de données qui stocke le référentiel.
** `-password password`: Spécifie le mot de passe nécessaire pour accéder à la base de données qui stocke le référentiel.
** `-port repo_port`: Indique le numéro de port TCP utilisé pour accéder à la base de données qui stocke le référentiel.


* *`-profile -name _profile_name_`*
+
Spécifie le profil auquel la base de données est associée.

+
Le `-profile` le paramètre inclut l'option suivante :

+
** `-name profilename`: Spécifie le nom du profil pour lequel vous allez définir le mot de passe.
** `-password password`: Spécifie le mot de passe nécessaire pour accéder au profil.


* *`-quiet`*
+
Affiche uniquement les messages d'erreur sur la console. La valeur par défaut est d'afficher les messages d'erreur et d'avertissement.

* *`-verbose`*
+
Affiche des messages d'erreur, d'avertissement et d'information sur la console.





== Exemple de commande pour la définition des informations d'identification du référentiel

L'exemple suivant définit les informations d'identification d'un référentiel.

[listing]
----

smsap credential set -repository -dbname SMSAPREPO -host hotspur -port 1527 -login -username chris
Password for chris@hotspur:1527/SMSAPREPO : ********
Confirm password for chris@hotspur:1527/SMSAPREPO : ********
----
[listing]
----
SMSAP-12345 [INFO ]: Updating credential cache for OS user "admin1"
SMSAP-12345 [INFO ]: Set repository credential for user "user1" on repo1@Host2.
Operation Id [Nff8080810da9018f010da901a0170001] succeeded.
----


== Exemple de commande pour la configuration des informations d'identification de l'hôte

Comme un identifiant d'hôte représente un identifiant de système d'exploitation réel, il doit inclure le nom d'utilisateur en plus du mot de passe.

[listing]
----
smsap credential set -host -name bismarck -username avida
Password for avida@bismarck : ********
Confirm password for avida@bismarck : ********
----