---
permalink: windows/reference-the-smosmsap-password-reset-command.html 
sidebar: sidebar 
keywords: run, password, reset, command, profile, smsap 
summary: 'Vous pouvez exécuter la commande de réinitialisation de mot de passe pour réinitialiser le mot de passe d"un profil.' 
---
= La commande smsap password reset
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez exécuter le mot de passe `reset command` pour réinitialiser le mot de passe d'un profil.



== Syntaxe

[listing]
----

smsap password reset
-profile profile
[-profile-password profile_password]
[-repository-hostadmin-password repository_hostadmin_password]
[-quiet | -verbose]
----


== Paramètres

* *`-profile _profile_`*
+
Indique le nom du profil pour lequel vous souhaitez réinitialiser le mot de passe.

* *`-profile-password _profile_password_`*
+
Spécifie le nouveau mot de passe pour le profil.

* *`-repository-hostadmin-password _admin_password_`*
+
Spécifie les informations d'identification de l'utilisateur autorisé avec le privilège administrateur local pour la base de données du référentiel.

* *`-quiet`*
+
Affiche uniquement les messages d'erreur dans la console. La valeur par défaut est d'afficher les messages d'erreur et d'avertissement.

* *`-verbose`*
+
Affiche les messages d'erreur, d'avertissement et d'information dans la console.


