---
permalink: windows/reference-the-smosmsapcredential-delete-command.html 
sidebar: sidebar 
keywords: command, delete, user, credential, particular, secure, resource, smsap 
summary: 'Cette commande supprime les informations d"identification de l"utilisateur pour une ressource sécurisée particulière.' 
---
= La commande smsap Credential delete
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cette commande supprime les informations d'identification de l'utilisateur pour une ressource sécurisée particulière.



== Syntaxe

[listing]
----

smsap credential delete
[-host -name host_name
-username username] |
[-repository
-dbname repo_service_name
-host repo_host
-login -username repo_username
-port repo_port] |
[-profile
-name profile_name]
[-quiet | -verbose]
----


== Paramètres

* *`-host _hostname_`*
+
Spécifie le nom du serveur hôte sur lequel SnapManager s'exécute.

+
Le `-host` le paramètre inclut les options suivantes :

+
** `-name host_name`: Indique le nom de l'hôte pour lequel vous allez supprimer le mot de passe.
** `-username user_name`: Indique le nom d'utilisateur sur l'hôte.


* *`-repository -dbname`*
+
Indique le nom de la base de données qui stocke le profil. Utilisez le nom global ou le SID.

+
Le `-repository` le paramètre inclut les options suivantes :

+
** `-dbnamerepo_service_name`: Indique le nom de la base de données qui stocke le profil. Utilisez le nom global ou le SID.
** `-host repo_host`: Indique le nom ou l'adresse IP du serveur hôte sur lequel s'exécute la base de données de référentiel.
** `-login-username repo_username`: Indique le nom d'utilisateur nécessaire pour accéder à la base de données qui stocke le référentiel.
** `-port repo_port`: Indique le numéro de port TCP utilisé pour accéder à la base de données qui stocke le référentiel.


* *`-profile -name _profile_name_`*
+
Spécifie le profil auquel la base de données est associée.

+
Le `-profile` le paramètre inclut l'option suivante :

+
** `-name _profilename_`: Spécifie le nom du profil pour lequel vous allez supprimer le mot de passe.


* *`-quiet`*
+
Affiche uniquement les messages d'erreur sur la console. La valeur par défaut est d'afficher les messages d'erreur et d'avertissement.

* *`-verbose`*
+
Affiche des messages d'erreur, d'avertissement et d'information sur la console.





== Exemple de commande

Cet exemple supprime les informations d'identification du profil.

[listing]
----
smsap credential delete -profile -name user1 -verbose
----
[listing]
----
SMSAP-20022 [INFO ]: Deleted credentials and repository mapping
 for profile "user1" in user credentials for "user1".
----
Cet exemple supprime les informations d'identification du référentiel.

[listing]
----
smsap credential delete -repository -dbname SMSAPREPO -host Host2
-login -username user1 -port 1521
----
[listing]
----
SMSAP-20023 [INFO ]: Deleted repository credentials for "user1@SMSAPREPO/wasp:1521"
and associated profile mappings in user credentials for "user1".
----
Cet exemple supprime les informations d'identification de l'hôte.

[listing]
----
smsap credential delete -host -name Host2
----
[listing]
----
SMSAP-20033 [INFO ]: Deleted host credentials for "Host2" in user credentials for "user1".
----