---
permalink: windows/reference-the-smosmsap-clone-update-command.html 
sidebar: sidebar 
keywords: command, update, information, clone, comment, smsap 
summary: Cette commande met à jour les informations relatives au clone. Vous pouvez mettre à jour le commentaire. 
---
= La commande smsap clone update
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cette commande met à jour les informations relatives au clone. Vous pouvez mettre à jour le commentaire.



== Syntaxe

[listing]
----

smsap clone update
-profile profile_name
[-label label | -id id]
-comment  commment_text
[-quiet | -verbose]
----


== Paramètres

* *`-profile _profile_name_`*
+
Spécifie le nom du profil contenant le clone à mettre à jour. Le profil contient l'identifiant de la base de données et d'autres informations sur la base de données.

* *`-id _id_`*
+
Spécifie l'ID du clone. L'ID est généré par SnapManager lors de la création d'un clone. Utilisez le `smsap clone list` Commande permettant d'afficher l'ID pour chaque clone.

* *`-label _label_`*
+
Spécifie le libellé du clone.

* *`-comment`*
+
Affiche le commentaire saisi dans le clone de création. Ce paramètre est facultatif.

* *`-quiet`*
+
Affiche uniquement les messages d'erreur sur la console. La valeur par défaut est d'afficher les messages d'erreur et d'avertissement.

* *`-verbose`*
+
Affiche des messages d'erreur, d'avertissement et d'information sur la console.





== Exemple de commande

L'exemple suivant met à jour le commentaire sur le clone.

[listing]
----
smsap clone update -profile anson.pcrac5
-label clone_pcrac51_20080820141624EDT  -comment See updated clone
----