---
permalink: windows/reference-copyright.html 
sidebar: sidebar 
keywords: copyright, information 
summary: Informations sur le copyright 
---
= Informations sur le copyright
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


Copyright © 1994 NetApp, Inc. Tous droits réservés. Imprimé aux États-Unis

Aucune partie de ce document protégé par copyright ne peut être reproduite sous quelque forme que ce soit ou par quelque moyen que ce soit (graphique, électronique ou mécanique, y compris par photocopie, enregistrement, bande ou stockage dans un système de récupération électronique--sans l'autorisation écrite préalable du détenteur du droit de copyright.

Les logiciels issus du matériel NetApp soumis à un copyright sont soumis aux conditions de non-responsabilité suivantes :

CE LOGICIEL EST FOURNI PAR NETAPP « EN L'ÉTAT » ET SANS GARANTIES EXPRESSES OU TACITES, Y COMPRIS LES GARANTIES TACITES DE QUALITÉ MARCHANDE ET D'ADÉQUATION À UN USAGE PARTICULIER, QUI SONT EXCLUES PAR LA PRÉSENTE. EN AUCUN CAS NETAPP NE SERA TENU POUR RESPONSABLE DE DOMMAGES DIRECTS, INDIRECTS, ACCESSOIRES, PARTICULIERS OU EXEMPLAIRES (Y COMPRIS L'ACHAT DE BIENS ET DE SERVICES DE SUBSTITUTION, LA PERTE DE JOUISSANCE, DE DONNÉES OU DE PROFITS) OU UNE INTERRUPTION D'ACTIVITÉ) QUELLES QU'EN SOIENT LA CAUSE ET LA DOCTRINE DE RESPONSABILITÉ, QU'IL S'AGISSE DE RESPONSABILITÉ CONTRACTUELLE, STRICTE OU DÉLICTUELLE (Y COMPRIS LA NÉGLIGENCE OU AUTRE) DÉCOULANT DE L'UTILISATION DE CE LOGICIEL, MÊME SI LA SOCIÉTÉ A ÉTÉ INFORMÉE DE LA POSSIBILITÉ DE TELS DOMMAGES.

NetApp se réserve le droit de modifier les produits décrits dans le présent document à tout moment et sans préavis. NetApp n'accepte aucune responsabilité découlant de l'utilisation des produits décrits dans le présent document, sauf accord explicite écrit de NetApp. L'utilisation ou l'achat de ce produit ne concède pas de licence dans le cadre de droits de brevet, de droits de marque commerciale ou de tout autre droit de propriété intellectuelle de NetApp.

Le produit décrit dans ce manuel peut être protégé par un ou plusieurs brevets américains étrangers ou par une demande en attente.

LÉGENDE DE RESTRICTION DES DROITS : l'utilisation, la duplication ou la divulgation par le gouvernement sont sujettes aux restrictions énoncées dans le sous-paragraphe (c)(1)(ii) de la clause Rights in Technical Data and Computer Software de DFARS 252.277-7103 (octobre 1988) et FAR 52-227-19 (juin 1987).
