---
permalink: windows/reference-the-smosmsapprofile-update-command.html 
sidebar: sidebar 
keywords: run, profile, update, command, information, exist, smsap 
summary: 'Vous pouvez exécuter la commande de mise à jour du profil pour mettre à jour les informations d"un profil existant.' 
---
= La commande smsap profile update
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez exécuter le `profile update` commande permettant de mettre à jour les informations d'un profil existant.



== Syntaxe

[listing]
----

smsap profile update
-profile profile
[-new-profile new_profile_name]
[-profile-password profile_password]
[-database
-dbname db_dbname
-host db_host
[-sid db_sid]
[-login
[-username db_username -password db_password -port db_port]
]
[{-rman  {-controlfile | {{-login
-username  rman_username
-password  rman_password }
[-tnsname  tnsname]}}} |
-remove-rman]


[-retain
[-hourly [-count n] [-duration m]]
[-daily [-count n] [-duration m]]
[-weekly [-count n] [-duration m]]
[-monthly [-count n] [-duration m]]]]
-comment comment
-snapname-patternpattern
[]
[-summary-notification]
[-notification
[-success
-email email_address1,email_address2
-subject subject_pattern]
[-failure
-email email_address1,email_address2
-subject subject_pattern]
[-separate-archivelog-backups
-retain-archivelog-backups
-hours  hours |
-days days |
-weeks weeks |
-months months
[]
[-include-with-online-backups | -no-include-with-online-backups]]
[-dump]
[-quiet | -verbose]
----


== Paramètres

* *`-profile _profile_`*
+
Spécifie le nom du profil. Ce nom peut comporter jusqu'à 30 caractères et doit être unique au sein de l'hôte.

* *`-profile-password _profile_password_`*
+
Spécifie le mot de passe du profil.

* *`-new-profile _new_profile_name_`*
+
Spécifie le nouveau nom que vous pouvez fournir pour un profil.

* *`-database`*
+
Indique les détails de la base de données que le profil décrit. Il s'agit de la base de données qui sera sauvegardée, restaurée, etc.

* *`-dbname _db_dbname_`*
+
Indique le nom de la base de données décrit par le profil. Vous pouvez utiliser le nom global ou l'identifiant système.

* *`-host _db_host_`*
+
Indique le nom ou l'adresse IP de l'ordinateur hôte sur lequel la base de données s'exécute.

* *`-sid _db_sid_`*
+
Indique l'identifiant système de la base de données décrit par le profil. Par défaut, SnapManager utilise le nom de la base de données comme identificateur système. Si l'identificateur système est différent du nom de la base de données, vous devez le spécifier à l'aide de l' `-sid` option.

* *`-login`*
+
Spécifie les détails de connexion au référentiel.

* *`-username _repo_username_`*
+
Indique le nom d'utilisateur requis pour accéder à la base de données du référentiel.

* *`-port _repo_port_`*
+
Spécifie le numéro de port TCP requis pour accéder à la base de données du référentiel.

* *`-database`*
+
Indique les détails de la base de données que le profil décrit. Il s'agit de la base de données qui sera sauvegardée, restaurée ou clonée.

* *`-dbname _db_dbname_`*
+
Indique le nom de la base de données décrit par le profil. Vous pouvez utiliser le nom global ou l'identifiant système.

* *`-host _db_host_`*
+
Indique le nom ou l'adresse IP de l'ordinateur hôte sur lequel la base de données s'exécute.

* *`-login`*
+
Spécifie les détails de connexion à la base de données.

* *`-username _db_username_`*
+
Indique le nom d'utilisateur requis pour accéder à la base de données décrit par le profil.

* *`-password _db_password_`*
+
Spécifie le mot de passe requis pour accéder à la base de données décrit par le profil.

* *`-port _db_port_`*
+
Spécifie le numéro de port TCP requis pour accéder à la base de données que le profil décrit.

* *`-retain [-hourly [-countn] [-duration m]] [-daily [-count n] [-duration m]] [-weekly [-count n][-duration m]] [-monthly [-count n][-duration m]]`*
+
Spécifie la classe de rétention (horaire, quotidien, hebdomadaire, mensuelle) pour une sauvegarde.

+
Pour chaque classe de rétention, un nombre de rétention, une durée de rétention ou les deux peuvent être spécifiés. La durée est exprimée en unités de la classe (par exemple, heures pour l'heure ou jours pour le quotidien). Par exemple, si l'utilisateur indique uniquement une durée de conservation de 7 pour les sauvegardes quotidiennes, SnapManager ne limite pas le nombre de sauvegardes quotidiennes du profil (car le nombre de rétention est 0), mais SnapManager supprimera automatiquement les sauvegardes quotidiennes créées il y a plus de 7 jours.

* *`-comment _comment_`*
+
Spécifie le commentaire pour un profil.

* *`-snapname-pattern _pattern_`*
+
Spécifie le modèle de nom pour les copies Snapshot. Vous pouvez également inclure du texte personnalisé, par exemple HAOPS pour les opérations hautement disponibles, dans tous les noms de copie Snapshot. Vous pouvez modifier le schéma de nommage des copies Snapshot lorsque vous créez un profil ou après sa création. La mise à jour de la grille s'applique uniquement aux copies Snapshot qui n'ont pas encore eu lieu. Les copies Snapshot qui existent conservent le modèle Snapname précédent. Vous pouvez utiliser plusieurs variables dans le texte du motif.

* *`-summary-notification`*
+
Indique que la notification par e-mail sommaire est activée pour le profil existant.

* *`-notification  [-success-email  _e-mail_address1,e-mail address2_  -subject  _subject_pattern_]`*
+
Active la notification par e-mail pour le profil existant afin que les e-mails soient reçus par les destinataires lorsque l'opération SnapManager réussit. Vous devez entrer une ou plusieurs adresses e-mail auxquelles les alertes e-mail seront envoyées et un modèle d'objet d'e-mail pour le profil existant.

+
Vous pouvez modifier le texte de l'objet lors de la mise à jour du profil ou inclure un objet personnalisé. L'objet mis à jour s'applique uniquement aux e-mails non envoyés. Vous pouvez utiliser plusieurs variables pour l'objet de l'e-mail.

* *`-notification  [-failure  -email  _e-mail_address1,e-mail address2_  -subject  _subject_pattern_]`*
+
Active la notification par e-mail pour le profil existant afin que les e-mails soient reçus par les destinataires en cas d'échec de l'opération SnapManager. Vous devez entrer une ou plusieurs adresses e-mail auxquelles les alertes e-mail seront envoyées et un modèle d'objet d'e-mail pour le profil existant.

+
Vous pouvez modifier le texte de l'objet lors de la mise à jour du profil ou inclure un objet personnalisé. L'objet mis à jour s'applique uniquement aux e-mails non envoyés. Vous pouvez utiliser plusieurs variables pour l'objet de l'e-mail.

* *`-separate-archivelog-backups`*
+
Sépare la sauvegarde du journal d'archivage de la sauvegarde des fichiers de données. Il s'agit d'un paramètre facultatif que vous pouvez fournir lors de la création du profil. Une fois les sauvegardes séparées, vous pouvez créer une sauvegarde de fichiers de données uniquement ou des journaux d'archivage uniquement.

* *`-retain-archivelog-backups -hours _hours_ | -days _days_ | -weeks _weeks_| -months _months_`*
+
Indique que les sauvegardes du journal d'archivage sont conservées en fonction de la durée de conservation du journal d'archivage (horaire, quotidien, hebdomadaire, mensuel).

* *`-include-with-online-backups | -no-include-with-online-backups`*
+
Indique que la sauvegarde du journal d'archivage est incluse avec la sauvegarde de base de données en ligne.

+
Indique que les sauvegardes du journal d'archivage ne sont pas incluses avec la sauvegarde de base de données en ligne.

* *`-dump`*
+
Indique que les fichiers de vidage sont collectés après l'opération de création de profil réussie.

* *`-quiet`*
+
Affiche uniquement les messages d'erreur dans la console. La valeur par défaut est d'afficher les messages d'erreur et d'avertissement.

* *`-verbose`*
+
Affiche les messages d'erreur, d'avertissement et d'information dans la console.





== Exemple

L'exemple suivant modifie les informations de connexion de la base de données décrites par le profil et la notification par e-mail est configurée pour ce profil :

[listing]
----
smsap profile update -profile SALES1 -database -dbname SALESDB
-sid SALESDB -login -username admin2 -password d4jPe7bw -port 1521
-host server1 -profile-notification -success -e-mail Preston.Davis@org.com -subject success
Operation Id [8abc01ec0e78ec33010e78ec3b410001] succeeded.
----