---
permalink: windows/reference-the-smosmsapbackup-verify-command.html 
sidebar: sidebar 
keywords: run, backup, verify, command, valid, format, oracle, smsap 
summary: Vous pouvez exécuter la commande backup verify pour vérifier si la sauvegarde est dans un format valide pour Oracle. 
---
= La commande smsap backup verify
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez exécuter le `backup verify` Commande pour vérifier si la sauvegarde est dans un format valide pour Oracle.



== Syntaxe

[listing]
----
smsap backup verify
-profile profile_name
[-label backup_name | [-id guid]
[-retain {-hourly | -daily | -weekly | -monthly | -unlimited}]
[-force]
[-dump]
[-quiet | -verbose]
----


== Paramètres

* *`-profile _profile_name_`*
+
Spécifie le profil pour lequel vous souhaitez vérifier une sauvegarde. Le profil contient l'identifiant de la base de données et d'autres informations sur la base de données.

* *`-id _guid_`*
+
Vérifie la sauvegarde à l'aide du GUID spécifié. Le GUID est généré par SnapManager lors de la création d'une sauvegarde. Vous pouvez utiliser le `smsap backup list` Commande pour afficher le GUID de chaque sauvegarde.

* *`-label _label_name_`*
+
Vérifie la sauvegarde avec l'étiquette spécifiée.

* *`-dump`*
+
Collecte les fichiers de vidage après l'opération de vérification de la sauvegarde réussie ou ayant échoué.

* *`-force`*
+
Force la base de données à l'état nécessaire pour effectuer l'opération de vérification.

* *`-quiet`*
+
Affiche uniquement les messages d'erreur dans la console. La valeur par défaut est d'afficher les messages d'erreur et d'avertissement.

* *`-verbose`*
+
Affiche les messages d'erreur, d'avertissement et d'information dans la console.





== Exemple

Voici un exemple de vérification de la sauvegarde :

[listing]
----
smsap backup verify -profile SALES1 -label full_backup_sales_May -quiet
----
[listing]
----
DBVERIFY - Verification starting : FILE = C:\SnapManager_auto_mounts\H-2012071400592312_0\smsap\datafile\data
----