---
permalink: windows/reference-the-smosmsapclone-template-command.html 
sidebar: sidebar 
keywords: command, create, clone, specification, template, smsap 
summary: Cette commande permet de créer un modèle de spécification clone. 
---
= La commande smsap clone template
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cette commande permet de créer un modèle de spécification clone.



== Syntaxe

[listing]
----

smsap clone template
-profile name
[-backup-id guid  | -backup-label backup_name]
[-quiet | -verbose]
----


== Paramètres

* *`-profile _name_`*
+
Spécifie la base de données dont vous souhaitez créer une spécification de clone. Le profil contient l'identifiant de la base de données et d'autres informations sur la base de données.

* *`-backup-id _guid_`*
+
Crée une spécification de clone à partir de la sauvegarde avec le GUID spécifié. Le GUID est généré par SnapManager lors de la création d'une sauvegarde. Utilisez le `smsap backup list` Commande pour afficher le GUID de chaque sauvegarde.

* *`-backup-label _backup_label_name_`*
+
Crée une spécification de clone à partir de la sauvegarde avec l'étiquette de sauvegarde spécifiée.

* *`-quiet`*
+
Affiche uniquement les messages d'erreur sur la console. La valeur par défaut est d'afficher les messages d'erreur et d'avertissement.

* *`-verbose`*
+
Affiche des messages d'erreur, d'avertissement et d'information sur la console.





== Exemple de commande

L'exemple suivant crée un modèle de spécification de clone à partir de la sauvegarde avec l'étiquette Full_Backup_sales_May. Une fois la commande smsap clone template terminée, le modèle de spécification clone est terminé.

[listing]
----
smsap clone template -profile SALES1 -backup-label full_backup_sales_May
Operation Id [8abc01ec0e79004b010e79006da60001] succeeded.
----