---
permalink: windows/task-authorizing-user-access-to-the-repository.html 
sidebar: sidebar 
keywords: snapmanager, enable, set, credential, user, repository, restrict, prevent, access, host, database, authorize, authorizing 
summary: 'SnapManager vous permet de définir les informations d"identification des utilisateurs de base de données pour accéder au référentiel. À l"aide des informations d"identification, vous pouvez restreindre ou empêcher l"accès aux hôtes, référentiels, profils et bases de données SnapManager.' 
---
= Autorisation de l'accès au référentiel
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager vous permet de définir les informations d'identification des utilisateurs de base de données pour accéder au référentiel. À l'aide des informations d'identification, vous pouvez restreindre ou empêcher l'accès aux hôtes, référentiels, profils et bases de données SnapManager.

Si vous définissez les informations d'identification à l'aide de la commande dataset, SnapManager ne vous invite pas à entrer un mot de passe.

Vous pouvez définir les informations d'identification de l'utilisateur lors de l'installation de SnapManager ou d'une version ultérieure.

. Saisissez la commande suivante :
+
`smsap credential set -repository -dbname repo_service_name -host repo_host -login -username repo_username [-password repo_password] -port repo_port`


