---
permalink: windows/task-restore-backups-from-an-alternate-location.html 
sidebar: sidebar 
keywords: restore, alternate, location, data, file, intermediate, system, active, backup 
summary: 'Vous pouvez effectuer une restauration à partir d"un autre emplacement pour restaurer les fichiers de données d"un système de fichiers intermédiaire vers un système de fichiers actif.' 
---
= Restaurez les sauvegardes à partir d'un autre emplacement
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez effectuer une restauration à partir d'un autre emplacement pour restaurer les fichiers de données d'un système de fichiers intermédiaire vers un système de fichiers actif.



== Ce dont vous aurez besoin

* Créez un fichier XML de spécification de restauration et spécifiez le type de méthode de restauration que vous souhaitez utiliser.




== Description de la tâche

Vous pouvez utiliser le `smsap backup restore` Et spécifiez le fichier XML de spécification de restauration que vous avez créé pour restaurer la sauvegarde à partir d'un autre emplacement.

.Étape
. Saisissez la commande suivante :
+
`*smsap backup restore -profile _profile_ -label _label_ -complete-alllogs -restorespec _restorespec_*`


