---
permalink: windows/task-configuring-history-for-backup-operation.html 
sidebar: sidebar 
keywords: snapmanager, sap, enable, maintain, history, operation, cli, gui, history, operation, report, configure, configuring 
summary: 'SnapManager pour SAP vous permet de conserver l"historique des opérations SnapManager à partir de l"interface de ligne de commande ou de l"interface graphique SnapManager. Vous pouvez afficher l"historique de l"opération SnapManager sous forme de rapport.' 
---
= Configuration de l'historique des opérations SnapManager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager pour SAP vous permet de conserver l'historique des opérations SnapManager à partir de l'interface de ligne de commande ou de l'interface graphique SnapManager. Vous pouvez afficher l'historique de l'opération SnapManager sous forme de rapport.

.Étape
. Pour configurer l'historique des opérations SnapManager, entrez la commande suivante :
+
`smsap history set -profile {-name, profile_name [profile_name1, profile_name2] | -all-repository-login [-passwordrepo_password] -usernamerepo_username-dbnamerepo_dbname-hostrepo_host-portrepo_port} -operation {-operationsoperation_name [operation_name1, operation_name2] | -all} -retain {-countretain_count | -dailyretain_daily | -weeklyretain_weekly | -monthlyretain_monthly} [-quiet | -verbose]`



[listing]
----

smsap
history set -profile -name PROFILE1 -operation -operations backup -retain -daily 6 -verbose
----
[listing]
----

smsap
history set -profile -name PROFILE1 -operation -all -retain -weekly 3 -verbose
----