---
permalink: windows/task-creating-an-oracle-user-for-the-target-database.html 
sidebar: sidebar 
keywords: create, oracle, user, sysdba, role, connext, database, perform, operation, creating, target 
summary: Vous devez créer un utilisateur Oracle avec le rôle sysdba qui se connecte à la base de données et effectue des opérations de base de données. 
---
= Création d'un utilisateur Oracle pour la base de données cible
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez créer un utilisateur Oracle avec le rôle sysdba qui se connecte à la base de données et effectue des opérations de base de données.

SnapManager peut utiliser n'importe quel utilisateur Oracle avec des privilèges sysdba qui existent dans la base de données cible, par exemple, l'utilisateur "sys" par défaut. Vous pouvez également créer un utilisateur dans la base de données cible à utiliser exclusivement par SnapManager.

. Connectez-vous à SQL *plus.
+
À l'invite de commande, entrez la commande suivante : `sqlplus '/ as sysdba'`

. Pour créer un utilisateur, par exemple smsap_oper avec le mot de passe administrateur, par exemple, adminpw1, entrez la commande suivante à l'invite SQL : `SQL> create user smsap_oper identified by adminpw1;`
. Accordez des privilèges sysdba à l'utilisateur Oracle en entrant la commande suivante : `SQL> grant sysdba to smsap_oper;`

