---
permalink: windows/task-create-database-backups.html 
sidebar: sidebar 
keywords: create, backup, database, portion, tablespace, data, file, control 
summary: Vous pouvez créer des sauvegardes de bases de données entières ou de parties de bases de données, y compris des espaces de stockage, des fichiers de données ou des fichiers de contrôle. 
---
= Créer des sauvegardes de bases de données
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez créer des sauvegardes de bases de données entières ou de parties de bases de données, y compris des espaces de stockage, des fichiers de données ou des fichiers de contrôle.



== Description de la tâche

SnapManager fournit des fonctionnalités de copie Snapshot pour les bases de données sur de nombreuses piles de stockage côté hôte, notamment NFS, Veritas et bien d'autres.

Les administrateurs peuvent éventuellement enregistrer des sauvegardes avec Oracle RMAN, ce qui facilite l'utilisation de RMAN pour restaurer et restaurer la base de données à des grains plus fins, tels que les blocs.

Lors de la définition du profil, vous pouvez personnaliser les noms des copies Snapshot créées par les sauvegardes de ce profil. Par exemple, vous pouvez insérer une chaîne de préfixe `*HOPS*` Pour indiquer les sauvegardes à haute exploitation.

En plus de définir des noms uniques pour les copies Snapshot créées par les sauvegardes, vous pouvez créer des étiquettes uniques pour les sauvegardes elles-mêmes. Lorsque vous créez une sauvegarde, il est conseillé de fournir un nom pour la sauvegarde, de sorte que vous disposez d'un moyen simple de l'identifier à l'aide du `-label` paramètre. Ce nom doit être unique pour toutes les sauvegardes créées dans un profil particulier. Le nom peut contenir des lettres, des chiffres, des traits de soulignement (_) et un trait d'Union (-). Il ne peut pas commencer par un tiret. Les étiquettes sont sensibles à la casse. Vous pouvez ajouter des informations telles que les variables d'environnement du système d'exploitation, la date du système et le type de sauvegarde.

Si vous ne fournissez pas d'étiquette, SnapManager crée un nom d'étiquette par défaut dans le formulaire `scope_mode_datestring`, où portée est pleine ou partielle et le mode est hors ligne, en ligne ou automatique (la lettre `c` pour froid, `h` pour chaud, ou `a` pour automatique).

À partir de SnapManager 3.4, vous pouvez fournir votre propre étiquette de sauvegarde en remplaçant l'étiquette de sauvegarde par défaut créée par SnapManager. Vous devez définir la valeur du `override.default.backup.pattern` paramètre sur *true* et spécifiez le nouveau libellé de sauvegarde dans le `new.default.backup.pattern` paramètre. Le modèle de libellé de sauvegarde peut contenir des mots clés tels que le nom de la base de données, le nom du profil, la portée, le mode et le nom d'hôte, qui doivent être séparés par un trait de soulignement. Par exemple : `new.default.backup.pattern=dbname_profile_hostname_scope_mode`.


NOTE: L'horodatage sera automatiquement inclus à la fin de l'étiquette générée.

Lorsque vous saisissez un commentaire, vous pouvez inclure des espaces et des caractères spéciaux. En revanche, lorsque vous saisissez une étiquette, n'incluez pas d'espaces ni de caractères spéciaux.

Pour chaque sauvegarde, SnapManager génère automatiquement un GUID, qui est une chaîne HEXADÉCIMALE de 32 caractères. Pour déterminer le GUID, vous devez exécuter le `backup list` commande avec `-verbose` option.

Vous pouvez créer une sauvegarde complète d'une base de données lorsqu'elle est en ligne ou hors ligne. Pour permettre à SnapManager de gérer la sauvegarde d'une base de données, qu'elle soit en ligne ou hors ligne, vous devez utiliser le `-auto` option.

Lors de la création d'une sauvegarde, si vous avez activé l'élagage et que la notification récapitulative a été activée dans le profil, deux e-mails distincts sont déclenchés. Un e-mail est pour l'opération de sauvegarde et l'autre pour l'élagage. Vous pouvez mettre ces e-mails en corrélation en comparant le nom de sauvegarde et l'ID de sauvegarde contenus dans ces e-mails.

Vous pouvez créer une sauvegarde à froid lorsque la base de données est à l'état d'arrêt. Si la base de données est dans un état monté, modifiez-la à l'état d'arrêt et effectuez la sauvegarde hors ligne (sauvegarde à froid).

SnapManager (3.2 ou version ultérieure) vous permet de sauvegarder les fichiers journaux d'archives séparément des fichiers de données, ce qui vous permet de gérer efficacement les fichiers journaux d'archivage.

Pour créer les sauvegardes du journal d'archivage séparément, vous devez créer un nouveau profil ou mettre à jour le profil existant pour séparer les sauvegardes du journal d'archivage à l'aide de l' `-separate-archivelog-backups` option. Le profil vous permet d'effectuer les opérations SnapManager suivantes :

* Créez une sauvegarde du journal d'archivage.
* Supprimer une sauvegarde du journal d'archivage.
* Montez une sauvegarde du journal d'archivage.
* Libérer une sauvegarde du journal d'archivage.


Les options de sauvegarde varient en fonction des paramètres de profil :

* L'utilisation d'un profil qui n'est pas séparé pour effectuer des sauvegardes de journaux d'archive séparément vous permet d'effectuer les opérations suivantes :
+
** Créer une sauvegarde complète.
** Créez une sauvegarde partielle.
** Spécifiez les destinations du journal d'archivage à sauvegarder pour les fichiers journaux d'archive.
** Spécifiez les destinations du journal d'archivage à exclure de la sauvegarde.
** Spécifiez les options d'élagage pour supprimer les fichiers journaux d'archive des destinations du journal d'archivage.


* L'utilisation d'un profil séparé pour effectuer des sauvegardes de journaux d'archives vous permet d'effectuer les opérations suivantes :
+
** Créez une sauvegarde de fichiers de données uniquement.
** Créer une sauvegarde archiveils uniquement.
** Lors de la création d'une sauvegarde de fichiers de données uniquement, incluez la sauvegarde du journal d'archivage ainsi que la sauvegarde des fichiers de données en ligne uniquement pour le clonage.
+
Si vous avez inclus des sauvegardes de journaux d'archives avec des fichiers de données dans la page *Paramètres de profil* de l'assistant *création de profil* à partir de l'interface utilisateur graphique SnapManager, Et si vous n'avez pas sélectionné l'option *Archivelugs* dans l'assistant *Backup Create*, SnapManager crée toujours la sauvegarde du journal d'archivage avec les fichiers de données pour toutes les sauvegardes en ligne.

+
Dans ce cas, à partir de l'interface de ligne de commande SnapManager, vous pouvez prendre en compte toutes les destinations de sauvegarde du journal d'archivage, à l'exception des destinations d'exclusion spécifiées dans le fichier de configuration SnapManager. Mais vous ne pouvez pas élaguer ces fichiers journaux d'archive. Toutefois, vous pouvez toujours utiliser le `-archivelogs` Option permettant de spécifier la destination du fichier journal des archives et de nettoyer les fichiers journaux des archives à partir de l'interface de ligne de commande SnapManager.

+
Si vous créez la sauvegarde à l'aide de `-auto` et spécifiez le `-archivelogs` SnapManager crée une sauvegarde en ligne ou hors ligne en fonction de l'état actuel de la sauvegarde.

+
*** SnapManager crée une sauvegarde hors ligne lorsque la base de données est hors ligne et n'inclut pas les fichiers journaux d'archivage dans la sauvegarde.
*** SnapManager crée une sauvegarde en ligne avec les fichiers journaux d'archivage lorsque la base de données est en ligne.


** Lors de la création de la sauvegarde archiveils uniquement :
+
*** Spécifiez la destination du journal d'archivage à sauvegarder avec la sauvegarde archiveils uniquement
*** Spécifiez les destinations du journal d'archivage à exclure de la sauvegarde des journaux d'archivage uniquement
*** Spécifiez les options d'élagage pour supprimer les fichiers journaux d'archive des destinations du journal d'archivage




* *Scénarios non pris en charge*
+
** Vous ne pouvez pas créer la sauvegarde archivelog uniquement avec une sauvegarde de fichiers de données hors ligne uniquement.
** Vous ne pouvez pas élaguer les fichiers journaux d'archive lorsque les fichiers journaux d'archive ne sont pas sauvegardés.
** Vous ne pouvez pas élaguer les fichiers journaux d'archive lorsque la zone de récupération Flash (FRA) est activée pour les fichiers journaux d'archive.
+
Si vous spécifiez l'emplacement du journal d'archivage dans la zone de récupération Flash, vous devez vous assurer que vous spécifiez également l'emplacement du journal d'archivage dans le `archive_log_dest` paramètre.






NOTE: Lors de la création de sauvegardes du journal d'archives, vous devez entrer les chemins de destination complets du journal d'archivage entre guillemets doubles et les chemins de destination séparés par des virgules. Le séparateur de chemin doit être donné sous la forme de deux barres obliques inverses (\\) au lieu d'une barre oblique.

Lorsque vous spécifiez le libellé pour la sauvegarde des fichiers de données en ligne avec la sauvegarde du journal d'archives incluse, le libellé est appliqué pour la sauvegarde des fichiers de données et la sauvegarde du journal d'archivage est suffixée (`_logs`). Ce suffixe peut être configuré en modifiant le paramètre `suffix.backup.label.with.logs` Dans le fichier de configuration SnapManager.

Par exemple, vous pouvez spécifier la valeur sous `suffix.backup.label.with.logs=arc` pour que la valeur par défaut _logs soit remplacée par `_arc`.

Si vous n'avez pas spécifié de destinations de journal d'archivage à inclure dans la sauvegarde, SnapManager inclut toutes les destinations de journal d'archivage configurées dans la base de données.

Si des fichiers journaux d'archives sont manquants dans l'une des destinations, SnapManager ignore tous ces fichiers journaux d'archives créés avant les fichiers journaux d'archives manquants, même si ces fichiers sont disponibles dans une autre destination de journal d'archivage.

Lors de la création de sauvegardes du journal d'archivage, vous devez spécifier les destinations du fichier journal d'archivage à inclure dans la sauvegarde et définir le paramètre de configuration pour inclure les fichiers journaux d'archivage toujours au-delà des fichiers manquants dans la sauvegarde.


NOTE: Par défaut, ce paramètre de configuration est défini sur *true* pour inclure tous les fichiers journaux d'archive, au-delà des fichiers manquants. Si vous utilisez vos propres scripts d'élagage ou si vous supprimez manuellement des fichiers journaux d'archive des destinations du journal d'archivage, vous pouvez désactiver ce paramètre afin que SnapManager puisse ignorer les fichiers journaux d'archive et poursuivre la sauvegarde.

SnapManager ne prend pas en charge les opérations SnapManager suivantes pour les sauvegardes des journaux d'archivage :

* Cloner la sauvegarde du journal d'archivage
* Restaurer la sauvegarde du journal d'archivage
* Vérifiez la sauvegarde du journal d'archivage


SnapManager prend également en charge la sauvegarde des fichiers journaux d'archive à partir des destinations de la zone de restauration Flash.

.Étape
. Saisissez la commande suivante :
+
`*smsap backup create -profile _profile_name_ {[-full {-online | -offline | -auto} [-retain {-hourly | -daily | -weekly | -monthly | -unlimited}] [-verify] | [-data [[-files _files_ [_files_]] | [-tablespaces _-tablespaces_ [_-tablespaces_]] [-datalabel _label_] {-online | -offline | -auto} [-retain {-hourly | [-daily | -weekly | -monthly | -unlimited]} [-verify] | [-archivelogs [-label _label_] [-comment _comment_] [-backup-dest _path1_ [,[_path2_]]] [-exclude-dest _path1_ [,_path2_]]] [-prunelogs {-all | -untilSCN _untilSCN_ | -until-date _yyyy-MM-dd:HH:mm:ss_ | -before {-months | -days | -weeks | -hours}} -prune-dest _prune_dest1_,[_prune_dest2_]] [-taskspec _taskspec_]} [-dump] [-force] [-quiet | -verbose]*`

+
|===
| Les fonctions que vous recherchez... | Alors... 


 a| 
*Spécifiez si vous souhaitez effectuer une sauvegarde d'une base de données en ligne ou hors ligne, plutôt que de permettre à SnapManager de gérer s'il est en ligne ou hors ligne*
 a| 
Spécifiez `-offline` pour effectuer une sauvegarde de la base de données hors ligne. Spécifiez `-online` pour effectuer une sauvegarde de la base de données en ligne.

Si vous utilisez ces options, vous ne pouvez pas utiliser `-auto` option.



 a| 
*Indiquez si vous souhaitez permettre à SnapManager de gérer la sauvegarde d'une base de données, qu'elle soit en ligne ou hors ligne*
 a| 
Spécifiez le `-auto` option. Si vous utilisez cette option, vous ne pouvez pas utiliser `--offline` ou `-online` option.



 a| 
*Spécifiez si vous souhaitez effectuer une sauvegarde partielle de fichiers spécifiques*
 a| 
 Specify the -data-files option and then list the files, separated by commas. For example, list the file names f1, f2, and f3 after the option.
Exemple de création d'une sauvegarde partielle des fichiers de données sur Windows

[listing]
----

smsap backup create -profile nosep -data -files "J:\\mnt\\user\\user.dbf" -online
-label partial_datafile_backup -verbose
----


 a| 
*Spécifiez si vous souhaitez effectuer une sauvegarde partielle d'espaces de stockage spécifiques*
 a| 
Spécifiez le `-data -tablespaces` et ensuite, énumérez les espaces de stockage, séparés par des virgules. Par exemple, utilisez ts1, ts2 et ts3 après l'option.

SnapManager prend en charge la sauvegarde des tablespaces en lecture seule. Lors de la création de la sauvegarde, SnapManager transforme l'espace table en lecture seule en lecture/écriture. Une fois la sauvegarde créée, les espaces de stockage sont modifiés en lecture seule.

Exemple de création d'une sauvegarde partielle de l'espace table

[listing]
----

smsap backup create -profile nosep -data -tablespaces tb2 -online -label partial_tablespace_bkup -verbose
----


 a| 
*Spécifiez si vous souhaitez créer une étiquette unique pour chaque sauvegarde au format suivant : Full_hot_mybackup_label*
 a| 
Pour Windows, vous pouvez saisir l'exemple suivant :

[listing]
----

smsap backup create -online -full -profile targetdb1_prof1
-label full_hot_my_backup_label   -verbose
----


 a| 
*Spécifiez si vous souhaitez créer une sauvegarde des fichiers journaux d'archives séparément des fichiers de données*
 a| 
Spécifiez les options et variables suivantes :

** `-archivelogs` crée une sauvegarde des fichiers journaux d'archives.
** `-backup-dest` spécifie les destinations du fichier journal d'archives à sauvegarder.
** `-exclude-dest` spécifie les destinations du journal d'archivage à exclure.
** `-label` indique le libellé de la sauvegarde du fichier journal d'archives.


[NOTE]
====
Vous devez fournir l'un ou l'autre `-backup-dest` ou le `-exclude-dest` option.

====
Si ces deux options sont associées à la sauvegarde, un message d'erreur s'affiche `You have specified an invalid backup option. Specify any one of the options: -backup-dest, or exclude-dest`.

Exemple de création séparée de sauvegardes de fichiers journaux d'archives sous Windows

[listing]
----

smsap backup create -profile nosep -archivelogs -backup-dest "J:\\mnt\\archive_dest_2\\" -label archivelog_backup -verbose
----


 a| 
*Spécifiez si vous souhaitez créer une sauvegarde des fichiers de données et des fichiers journaux d'archive ensemble*
 a| 
Spécifiez les options et variables suivantes :

** `-data` pour spécifier les fichiers de données.
** `-archivelogs` option permettant de spécifier les fichiers journaux d'archive. Exemple de sauvegarde simultanée de fichiers de données et d'archivage de fichiers journaux sur Windows
+
[listing]
----

smsap backup create -profile nosep -data -online -archivelogs -backup-dest "J:\\mnt\\archive_dest_2\\" -label data_arch_backup
-verbose
----




 a| 
*Spécifiez si vous souhaitez élaguer les fichiers journaux d'archive lors de la création d'une sauvegarde*
 a| 
Spécifiez les options et variables suivantes :

** `-prunelogs` indique de supprimer les fichiers journaux d'archive des destinations du journal d'archivage.
+
*** `-all` indique de supprimer tous les fichiers journaux d'archive des destinations du journal d'archivage.
*** `-until-scnuntil-scn` Indique de supprimer les fichiers journaux d'archive jusqu'à ce qu'un SCN spécifié soit supprimé.
*** `-until-dateyyyy-MM-dd:HH:mm:ss` indique de supprimer les fichiers journaux d'archives jusqu'à la période spécifiée.
*** `-before` option indique de supprimer les fichiers journaux d'archives avant la période spécifiée (jours, mois, semaines, heures).
*** `-prune-destprune_dest1,[prune_dest2` indique de supprimer les fichiers journaux d'archive des destinations du journal d'archivage lors de la création de la sauvegarde.




[NOTE]
====
Vous ne pouvez pas élaguer les fichiers journaux d'archive lorsque la zone de récupération Flash (FRA) est activée pour les fichiers journaux d'archive.

====
Exemple de suppression de tous les fichiers journaux d'archives lors de la création d'une sauvegarde sous Windows

[listing]
----

smsap backup create -profile nosep
 -archivelogs -label archive_prunebackup1 -backup-dest "E:\\oracle\\MDV\\oraarch\\MDVarch,J:\\
" -prunelogs -all -prune-dest "E:\\oracle\\MDV\\oraarch\\MDVarch,J:\\" -verbose
----


 a| 
*Spécifiez si vous souhaitez ajouter un commentaire sur la sauvegarde*
 a| 
Spécifiez `-comment` suivi de la chaîne de description.



 a| 
*Spécifiez si vous voulez forcer la base de données à l'état que vous avez spécifié pour la sauvegarder, quel que soit l'état en cours*
 a| 
Spécifiez le `-force` option.



 a| 
*Spécifiez si vous voulez vérifier la sauvegarde en même temps que vous la créez*
 a| 
Spécifiez le `-verify` option.



 a| 
*Spécifiez si vous souhaitez collecter les fichiers de vidage après l'opération de sauvegarde de la base de données*
 a| 
Spécifiez `-dump` à la fin de la commande backup create.

|===




== Exemple

[listing]
----
smsap backup create -profile targetdb1_prof1 -full -online -force  -verify
----