---
permalink: windows/task-customizing-the-email-subject-for-an-existing-profile.html 
sidebar: sidebar 
keywords: snapmanager, enable, customize, email, subject, pattern, exist, profile, applicable, update, customizing 
summary: 'SnapManager vous permet de personnaliser le modèle d"objet d"un e-mail pour un profil existant en mettant à jour ce profil. Ce modèle d"objet personnalisé est applicable uniquement au profil mis à jour.' 
---
= Personnalisation de l'objet de l'e-mail pour un profil existant
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager vous permet de personnaliser le modèle d'objet d'un e-mail pour un profil existant en mettant à jour ce profil. Ce modèle d'objet personnalisé est applicable uniquement au profil mis à jour.

. Saisissez la commande suivante :
+
`smsap profile update -profileprofile [-profile-passwordprofile_password][-database-dbnamedb_dbname-host db_host [-siddb_sid] [-login -usernamedb_username-password db_password-port db_port]] [{-rman{-controlfile | {-login  -usernamerman_username-password  rman_password-tnsname  rman_tnsname}}} | -remove-rman] [-retain [-hourly [-countn] [-durationm]] [-daily [-countn] [-durationm]] [-weekly [-countn] [-durationm]] [-monthly [-countn] [-durationm]]] [-commentcomment][-snapname-patternpattern][[-protect [-protection-policypolicy_name]]| [[-noprotect]] [-notification [-success-emailemail_address1,email_address2-subjectsubject_pattern] [-failure-emailemail_address1,email_address2-subjectsubject_pattern]]`


