---
permalink: windows/task-update-target-database-hostname-associated-with-a-profile.html 
sidebar: sidebar 
keywords: snapmanager, sap, provide, ability, update, host, name, target, database, profile, associate 
summary: 'SnapManager (3.2 ou version ultérieure) pour SAP permet de mettre à jour le nom d"hôte de la base de données cible dans le profil SnapManager.' 
---
= Mettez à jour le nom d'hôte de la base de données cible associé à un profil
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager (3.2 ou version ultérieure) pour SAP permet de mettre à jour le nom d'hôte de la base de données cible dans le profil SnapManager.



== Ce dont vous avez besoin

* Le répertoire personnel de l'utilisateur local doit connaître les mappages de profil à référentiel.
* Les sessions de l'interface utilisateur graphique de SnapManager doivent être fermées.




== Description de la tâche

Vous pouvez mettre à jour le profil avec le nouveau nom d'hôte en utilisant uniquement l'interface de ligne de commande.

*Les scénarios ne sont pas pris en charge pour modifier le nom d'hôte de la base de données cible dans le profil*

Les scénarios suivants ne sont pas pris en charge pour la modification du nom d'hôte de la base de données cible dans le profil :

* Modification du nom d'hôte de la base de données cible à l'aide de l'interface graphique SnapManager
* Reprise de la base de données du référentiel après la mise à jour du nom d'hôte de la base de données cible du profil
* Mise à jour de plusieurs profils pour un nouveau nom d'hôte de base de données cible en exécutant une seule commande
* Modification du nom d'hôte de la base de données cible lors de l'exécution d'une opération SnapManager



NOTE: Après avoir mis à jour le nom d'hôte de la base de données cible dans le profil, seul le nom d'hôte de la base de données cible est modifié. Tous les autres paramètres de configuration définis sur le profil sont conservés.

Une fois que vous avez mis à jour le nom d'hôte de la base de données cible, vous ne pouvez pas supprimer ou démonter la sauvegarde si le clone ou la sauvegarde montée n'est pas disponible dans le nouvel hôte. Dans de tels cas, l'exécution des opérations SnapManager depuis le nouvel hôte entraîne une défaillance, ainsi que des entrées obsolètes dans l'hôte précédent. Pour effectuer des opérations SnapManager, vous devez revenir au nom d'hôte précédent en utilisant `profile update`.

.Étapes
. Saisissez la commande suivante :
+
`*smsap profile update -profile _profile_ [-profile-password _profile_password_][-database -dbname _db_dbname_ -host _db_host_ [-sid _db_sid_] [-login-username _db_username_ -password _db_password_ -port _db_port_]] [{-rman{-controlfile | {-login-username _rman_username_ -password _rman_password_ -tnsname _rman_tnsname_}}} | -remove-rman] [-retain [-hourly [-count _n_] [-duration _m_]] [-daily [-count _n_] [-duration _m_]] [-weekly [-count _n_] [-duration _m_]] [-monthly [-count _n_] [-duration _m_]]] [-comment _comment_][-snapname-pattern _pattern_][-summary-notification] [-notification [-success -email _email_address1_, _email_address2_ -subject _subject_pattern_] [-failure -email _email_address1_, _email_address2_ -subject _subject_pattern_]] [-separate-archivelog-backups-retain-archivelog-backups -hours _hours_ | -days _days_ | -weeks _weeks_| -months _months_ [-protect [-include-with-online-backups | -no-include-with-online-backups]] [-dump]*`

+
Les autres options de cette commande sont les suivantes :

+
[`-force`] [`-noprompt`]

+
[`quiet` | `-verbose`]

+
|===
| Les fonctions que vous recherchez... | Alors... 


 a| 
*Changer le nom d'hôte de la base de données cible*
 a| 
Spécifiez `-host _new_db_host_`

|===
. Pour afficher le nom d'hôte de la base de données cible du profil, entrez la commande suivante :
+
`smsap profile show`


