---
permalink: windows/task-resetting-profile-password.html 
sidebar: sidebar 
keywords: reset, profile, password, remember 
summary: Vous pouvez réinitialiser le mot de passe du profil si vous ne vous souvenez pas du mot de passe que vous avez fourni lors de la création du profil. 
---
= Réinitialisation du mot de passe du profil
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez réinitialiser le mot de passe du profil si vous ne vous souvenez pas du mot de passe que vous avez fourni lors de la création du profil.

* Vous devez vous assurer que le serveur SnapManager est exécuté sur la base de données du référentiel.
* Vous devez disposer des informations d'identification d'administrateur local de l'hôte sur lequel réside la base de données du référentiel.
* Vous devez vous assurer que le profil n'est pas utilisé pour toute opération lorsque le mot de passe est réinitialisé pour ce profil.


Vous pouvez réinitialiser le mot de passe à partir de l'interface de ligne de commandes ou de l'interface graphique de SnapManager. Lors de la réinitialisation du mot de passe, SnapManager interroge le serveur SnapManager sur l'hôte du référentiel pour identifier le système d'exploitation de l'hôte du référentiel. Vous devez entrer les informations d'identification de l'utilisateur autorisé pour vous connecter à l'hôte du référentiel. Le serveur SnapManager authentifie les utilisateurs à l'aide des informations d'identification de leur administrateur local sur la base de données du référentiel. Lorsque l'authentification est réussie, SnapManager réinitialise le mot de passe du profil sur le serveur SnapManager avec le nouveau mot de passe.


NOTE: SnapManager ne conserve pas l'historique des opérations de réinitialisation du mot de passe.

. Réinitialisez le mot de passe du profil en entrant la commande suivante :
+
`smsap password reset -profileprofile [-profile-passwordprofile_password] [-repository-hostadmin-passwordadmin_password]`


