---
permalink: windows/task-unmounting-backups.html 
sidebar: sidebar 
keywords: snapmanager, automatic, unmount, backup, available, external, tool, oracle, recovery, manager, rman, file, remove, access 
summary: 'SnapManager démonte automatiquement la sauvegarde pour la rendre indisponible au serveur hôte. SnapManager vous permet également de désinstaller si vous utilisez un outil externe, tel qu"Oracle Recovery Manager \(RMAN\), d"accéder aux fichiers de la sauvegarde et de modifier l"état de la sauvegarde pour supprimer l"accès.' 
---
= Démontage des sauvegardes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager démonte automatiquement la sauvegarde pour la rendre indisponible au serveur hôte. SnapManager vous permet également de démonter si vous utilisez un outil externe, tel qu'Oracle Recovery Manager (RMAN), pour accéder aux fichiers de la sauvegarde, et pour modifier l'état de la sauvegarde afin de supprimer l'accès.

Vous pouvez éventuellement collecter les fichiers de vidage après une opération de sauvegarde réussie ou ayant échoué.

.Étape
. Saisissez la commande suivante :
+
`smsap backup unmount -profile profile_name {labellabel [data | -archivelogs] | -idid} [-quiet | -verbose]`



*Informations connexes*

xref:reference-the-smosmsapbackup-unmount-command.adoc[La commande smsap backup unshunshunt]
