---
permalink: windows/task-restoring-backups-from-an-alternate-location.html 
sidebar: sidebar 
keywords: restore, alternate, location, data, file, intermediate, system, active, restoring, backup 
summary: 'Vous pouvez effectuer une restauration à partir d"un autre emplacement pour restaurer les fichiers de données d"un système de fichiers intermédiaire vers un système de fichiers actif.' 
---
= Restauration des sauvegardes à partir d'un autre emplacement
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez effectuer une restauration à partir d'un autre emplacement pour restaurer les fichiers de données d'un système de fichiers intermédiaire vers un système de fichiers actif.

* Créez un fichier XML de spécification de restauration et spécifiez le type de méthode de restauration que vous souhaitez utiliser.


Vous pouvez utiliser la commande smsap backup restore et spécifier le fichier XML de spécification de restauration que vous avez créé pour restaurer la sauvegarde à partir d'un autre emplacement.

. Saisissez la commande suivante :
+
`smsap backup restore -profileprofile-labellabel-complete-alllogs-restorespecrestorespec`



*Informations connexes*

xref:reference-the-smosmsapbackup-restore-command.adoc[La commande smsap backup restore]
