---
permalink: windows/task-enable-autosupport-in-snapmanager.html 
sidebar: sidebar 
keywords: enable, autosupport, storage, system, receive, message, snapmanager, server, successful, backup, operation, enable 
summary: Vous devez activer AutoSupport, de sorte que les systèmes de stockage reçoivent des messages du serveur SnapManager pour chaque opération de sauvegarde réussie. 
---
= Activez AutoSupport dans SnapManager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez activer AutoSupport, de sorte que les systèmes de stockage reçoivent des messages du serveur SnapManager pour chaque opération de sauvegarde réussie.



== Description de la tâche

AutoSupport peut être activé de deux manières :

* Par défaut, la nouvelle installation de SnapManager ne contient pas `auto_support.on` paramètre dans le `smsap.config` fichier de configuration. Cela implique que AutoSupport est activé.
* Vous pouvez configurer manuellement le `auto_support.on` paramètre.


.Étapes
. Arrêtez le serveur SnapManager.
. Dans le `smsap.config` fichier de configuration, définissez la valeur du `auto_support.on` Paramètre à *TRUE*.
+
*Exemple*

+
auto_support.on=VRAI

. Redémarrez le serveur SnapManager.

