---
permalink: windows/task-configure-history-for-backup-operation.html 
sidebar: sidebar 
keywords: snapmanager, sap, enable, maintain, history, operation, cli, gui, history, operation, report, configure 
summary: 'SnapManager pour SAP vous permet de conserver l"historique des opérations SnapManager à partir de l"interface de ligne de commande ou de l"interface graphique SnapManager. Vous pouvez afficher l"historique de l"opération SnapManager sous forme de rapport.' 
---
= Configurer l'historique des opérations SnapManager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager pour SAP vous permet de conserver l'historique des opérations SnapManager à partir de l'interface de ligne de commande ou de l'interface graphique SnapManager. Vous pouvez afficher l'historique de l'opération SnapManager sous forme de rapport.

.Étape
. Pour configurer l'historique des opérations SnapManager, entrez la commande suivante :
+
`*smsap history set -profile {-name, _profile_name_ [_profile_name1_, _profile_name2_] | _-all_ -repository -login [-password _repo_password_] -username _repo_username_ -dbname _repo_dbname_ -host _repo_host_ -port _repo_port_} -operation {-operations _operation_name_ [_operation_name1_, _operation_name2_] | -all} -retain {-count _retain_count_ | -daily _retain_daily_ | -weekly _retain_weekly_ | -monthly _retain_monthly_} [-quiet | -verbose]*`



[listing]
----

        smsap
history set -profile -name PROFILE1 -operation -operations backup -retain -daily 6 -verbose
----
[listing]
----

        smsap
history set -profile -name PROFILE1 -operation -all -retain -weekly 3 -verbose
----