---
permalink: windows/task-deleting-backups.html 
sidebar: sidebar 
keywords: delete, backup, free, space, occupy, remove, snapshot, copies, copy, volume, deleting 
summary: 'Vous devez supprimer les sauvegardes lorsque vous n"en avez plus besoin, ce qui libère l"espace occupé par ces sauvegardes. Si vous supprimez des sauvegardes, vous réduisez la probabilité d"atteindre la limite de 255 copies Snapshot par volume.' 
---
= Suppression de sauvegardes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez supprimer les sauvegardes lorsque vous n'en avez plus besoin, ce qui libère l'espace occupé par ces sauvegardes. Si vous supprimez des sauvegardes, vous réduisez la probabilité d'atteindre la limite de 255 copies Snapshot par volume.

* Vous devez vous assurer que la sauvegarde n'a pas été utilisée pour créer un clone.


Vous pouvez supprimer les sauvegardes conservées sans limite de temps sans modifier la classe de rétention.

Vous pouvez éventuellement collecter les fichiers de vidage après l'opération de suppression de sauvegarde réussie ou ayant échoué.

Si vous souhaitez supprimer les sauvegardes du journal d'archivage, vous devez vérifier la durée de conservation définie pour la sauvegarde du journal d'archivage. Si la sauvegarde du journal d'archivage est dans la durée de conservation et que les fichiers journaux d'archive sont nécessaires pour la récupération d'une base de données restaurée, vous ne pouvez pas supprimer la sauvegarde du journal d'archivage.

. Vérifiez que les opérations sont terminées en entrant la commande suivante : `smsap operation list -profileprofile_name-dump-quiet-verbose`
. Pour supprimer une sauvegarde, entrez la commande suivante :``smsap backup delete -profile profile_name [-label label [data | -archivelogs] | -idid | -all] [-force] [ -dump] [-quiet | -verbose]``
+
Utilisez l'option -force pour forcer la suppression de la sauvegarde. Le fait de forcer la suppression d'une sauvegarde dont les opérations sont incomplètes peut laisser la sauvegarde dans un état incohérent.


