---
permalink: windows/task-free-backups.html 
sidebar: sidebar 
keywords: free, backup, delete, snapshot, copies, copy, metadata, function, space, smsap 
summary: 'Vous pouvez libérer des sauvegardes, qui suppriment les copies Snapshot sans supprimer les métadonnées de sauvegarde. Cette fonction libère l"espace occupé par la sauvegarde. Vous pouvez utiliser la commande smsap backup free pour libérer les sauvegardes.' 
---
= Des sauvegardes gratuites
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez libérer des sauvegardes, qui suppriment les copies Snapshot sans supprimer les métadonnées de sauvegarde. Cette fonction libère l'espace occupé par la sauvegarde. Vous pouvez utiliser smsap `backup free` pour libérer les sauvegardes.



== Ce dont vous aurez besoin

Pour qu'une sauvegarde puisse être déautorisée, vous devez vous assurer que :

* La sauvegarde a réussi
* La sauvegarde ne doit pas être montée
* La sauvegarde ne contient pas de clones
* La sauvegarde ne doit pas être conservée au moyen d'une stratégie de conservation illimitée
* La sauvegarde n'est pas déjà libérée




== Description de la tâche

Vous pouvez spécifier le `-dump` option en tant que paramètre facultatif pour collecter les fichiers de vidage après l'opération de sauvegarde libre réussie ou échoué.

.Étape
. Saisissez la commande suivante :
+
`*smsap backup free -profile _profile_name_ {-label _label_ [data | -archivelogs] | -id _id_ | -all} -force[-dump] [-quiet] [-force]*`


