---
permalink: unix-administration/concept-managing-security-and-credentials.html 
sidebar: sidebar 
keywords: manage, security, snapmanager, apply, authentication, role-base, access, control, rbac, credential, management 
summary: 'Il est possible de gérer la sécurité dans SnapManager en appliquant l"authentification des utilisateurs et le contrôle d"accès basé sur des rôles (RBAC). La méthode d"authentification utilisateur vous permet d"accéder à des ressources telles que des référentiels, des hôtes et des profils. Le RBAC vous permet de restreindre les opérations que SnapManager peut réaliser sur les volumes et les LUN contenant les fichiers de données de votre base de données.' 
---
= Sécurité et gestion des identifiants
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez gérer la sécurité dans SnapManager par l'application d'authentificationet de contrôle d'accès basé sur des rôles (RBAC). La méthode d'authentification utilisateur vous permet d'accéder à des ressources telles que des référentiels, des hôtes et des profils. Le RBAC vous permet de restreindre les opérations que SnapManager peut réaliser sur les volumes et les LUN contenant les fichiers de données de votre base de données.

Lorsque vous effectuez une opération à l'aide de l'interface de ligne de commande ou de l'interface utilisateur graphique, SnapManager récupère les informations d'identification des référentiels et profils. SnapManager enregistre les informations d'identification des installations précédentes.

Le référentiel et les profils peuvent être sécurisés par un mot de passe. Un identifiant est le mot de passe configuré pour l'utilisateur pour un objet et le mot de passe n'est pas configuré sur l'objet lui-même.

Vous pouvez gérer l'authentification et les informations d'identification en effectuant les tâches suivantes :

* Gérez l'authentification des utilisateurs à l'aide d'invites de mot de passe lors des opérations ou à l'aide de `smsap credential set` commande.
+
Définissez les informations d'identification d'un référentiel, d'un hôte ou d'un profil.

* Affichez les informations d'identification qui régissent les ressources auxquelles vous avez accès.
* Effacez les informations d'identification d'un utilisateur pour toutes les ressources (hôtes, référentiels et profils).
* Supprimer les informations d'identification d'un utilisateur pour des ressources individuelles (hôtes, référentiels et profils).


Vous pouvez gérer l'accès basé sur les rôles en effectuant les tâches suivantes :

* Activez le RBAC pour SnapManager à l'aide de SnapDrive.
* Affectez les utilisateurs aux rôles et définissez les fonctions de rôle à l'aide de la console Operations Manager.
* Si vous le souhaitez, vous pouvez activer SnapManager pour stocker des mots de passe cryptés en modifiant le `smsap.config file`.


Si protection Manager est installé, l'accès aux fonctions est affecté de la manière suivante :

* Si protection Manager est installé, lorsque vous créez un profil de base de données, SnapManager crée un jeu de données et remplit le jeu de données avec les volumes qui contiennent les fichiers de base de données.
+
Après une opération de sauvegarde, SnapManager synchronise le contenu du dataset avec les fichiers de base de données.

* Si protection Manager n'est pas installé, SnapManager ne peut pas créer de jeu de données et vous ne pouvez pas définir de protection sur les profils.

