---
permalink: unix-administration/concept-advantages-and-disadvantages-of-using-fast-restore.html 
sidebar: sidebar 
keywords: dba, aware, advantage, disadvantage, volume-base, fast, restore, disadvantage 
summary: 'Les administrateurs de bases de données doivent connaître les avantages et les inconvénients liés à l"utilisation de restaurations rapides basées sur les volumes.' 
---
= Avantages et inconvénients de la restauration rapide
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les administrateurs de bases de données doivent connaître les avantages et les inconvénients liés à l'utilisation de restaurations rapides basées sur les volumes.

La restauration de sauvegardes de bases de données à l'aide de restaurations rapides offre les avantages suivants :

* Les restaurations basées sur les volumes réduisent le temps nécessaire à la restauration des sauvegardes.
* SnapManager permet de vérifier rapidement l'éligibilité à la restauration. SnapManager analyse la sauvegarde de la base de données et affiche des informations relatives à la possibilité d'effectuer la restauration basée sur les volumes.
* Vous pouvez prévisualiser l'opération de restauration et décider de poursuivre le chemin recommandé ou de remplacer la recommandation par le processus sélectionné.


La restauration de sauvegardes de bases de données à l'aide de restaurations rapides présente les inconvénients suivants :

* L'ensemble du système de fichiers est rétabli, y compris les fichiers qui n'ont pas été considérés comme faisant partie de la sauvegarde. Les autres fichiers, systèmes de fichiers ou LUN du volume seront également restaurés.
* SnapManager supprime toutes les copies Snapshot qui ont été effectuées après la restauration de la copie Snapshot. En effet, vous perdez l'historique après la date de la copie Snapshot. Par exemple, vous ne pouvez pas restaurer la sauvegarde du mardi si vous avez déjà restauré la sauvegarde du lundi.


Vous pouvez éviter les inconvénients en suivant les recommandations suivantes :

* Optimisez la disposition des bases de données selon les meilleures pratiques.
* Protection des sauvegardes sur un système de stockage secondaire Toutefois, si vous supprimez des copies Snapshot du stockage primaire, vous ne pouvez pas utiliser de restaurations rapides pour les restaurer à partir du stockage secondaire.

