---
permalink: unix-administration/reference-the-smosmsapprofile-sync-command.html 
sidebar: sidebar 
keywords: command, load, profile-to-repository, mappings, repository, file, home, directory, local, host, smsap 
summary: 'Cette commande charge les mappages profil-référentiel pour ce référentiel dans un fichier de votre répertoire personnel sur l"hôte local.' 
---
= La commande smsap profile sync
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cette commande charge les mappages profil-référentiel pour ce référentiel dans un fichier de votre répertoire personnel sur l'hôte local.



== Syntaxe

[listing, subs="+macros"]
----
pass:quotes[smsap profile sync
-repository
-dbname _repo_service_name_
-host _repo_host_
-port _repo_port_
-login
-username _repo_username_                  [-quiet | -verbose]]
----


== Paramètres

* ``*-repository*``
+
Les options suivantes -repository spécifient les détails de la base de données pour le référentiel.

* ``*-dbname _repo_service_name_*``
+
Spécifie la base de données du référentiel pour que le profil se synchronise.

* ``*-host*``
+
Spécifie l'hôte de base de données.

* ``*-port*``
+
Spécifie le port de l'hôte.

* ``*-login*``
+
Spécifie le processus de connexion pour l'utilisateur hôte.

* ``*-username*``
+
Spécifie le nom d'utilisateur de l'hôte.

* ``*-quiet*``
+
Affiche uniquement les messages d'erreur sur la console. La valeur par défaut est d'afficher les messages d'erreur et d'avertissement.

* ``*-verbose*``
+
Affiche des messages d'erreur, d'avertissement et d'information sur la console.





== Exemple de commande

L'exemple suivant montre le résultat de la commande pour synchroniser les mappages profil-référentiel de la base de données.

[listing]
----
smsap profile sync -repository -dbname smrepo -host Host2 -port 1521 -login -username user2
SMSAP-12345 [INFO ]: Loading profile mappings for repository "user2@Host2:smrepo" into cache for OS User "admin".
Operation Id [Nff8080810da9018f010da901a0170001] succeeded.
----