---
permalink: unix-administration/reference-troubleshooting-snapdrive-issues.html 
sidebar: sidebar 
keywords: common, issue, snapmanager, snapdrive, troubleshooting, product 
summary: Si vous utilisez SnapManager avec des produits SnapDrive, vous pouvez résoudre quelques problèmes courants. 
---
= Résolution des problèmes de SnapDrive
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous utilisez SnapManager avec des produits SnapDrive, vous pouvez résoudre quelques problèmes courants.

Tout d'abord, vous devez déterminer si le problème est lié à SnapManager pour SAP ou SnapDrive. Si le problème est une erreur SnapDrive, SnapManager pour SAP affiche un message d'erreur similaire à :

[listing]
----
SMSAP-12111: Error executing snapdrive command "<snapdrive command>": <snapdrive error>
----
Voici un exemple de message d'erreur SnapDrive où `SMSAP-12111` Est le numéro d'erreur SnapManager. Le `0001-770` Le schéma de numérotation représente les erreurs SnapDrive pour UNIX.

[listing]
----
SMSAP-12111: Error executing snapdrive command
"/usr/sbin/snapdrive snap restore -file
/mnt/pathname/ar_anzio_name_10gR2_arrac1/data/undotbs02.dbf -snapname pathname.company.com:
/vol/ar_anzio_name_10gR2_arrac1:
TEST_ARRAC1_YORKTOW_arrac12_F_C_0_8abc01b20f9ec03d010f9ec06bee0001_0": 0001-770
Admin error: Inconsistent number of files returned when listing contents of
/vol/ar_anzio_name_10gR2_arrac1/.snapshot/
TEST_ARRAC1_YORKTOW_arrac12_F_C_0_8abc01b20f9ec03d010f9ec06bee0001_0/data
on filer pathname.
----
Les messages d'erreur SnapDrive les plus courants relatifs à la détection de LUN, aux problèmes de configuration et à l'espace sont les suivants : Si vous recevez l'une de ces erreurs, reportez-vous au chapitre Dépannage du _Guide d'installation et d'administration de SnapDrive_.

[cols="3a,1a"]
|===
| Symptôme | Explication 


 a| 
``0001-136 Admin error: Unable to log on to filer: <filer> Please set user name and/or password for <filer>``
 a| 
Configuration initiale de SnapDrive



 a| 
`0001-382 Admin error: Multipathing rescan failed`
 a| 
Erreur de détection de LUN



 a| 
`0001-462 Admin error: Failed to unconfigure multipathing for <LUN>: spd5: cannot stop device. Device busy.`
 a| 
Erreur de détection de LUN



 a| 
``0001-476 Admin error: Unable to discover the device associated with ... 0001-710 Admin error: OS refresh of LUN failed ...``
 a| 
Erreur de détection de LUN



 a| 
``0001-680 Admin error: Host OS requires an update to internal data to allow LUN creation or connection. Use 'snapdrive config prepare luns' or update this information manually...``
 a| 
Erreur de détection de LUN



 a| 
`0001-817 Admin error: Failed to create volume clone ... : FlexClone not licensed`
 a| 
Configuration initiale de SnapDrive



 a| 
``0001-878 Admin error: HBA assistant not found. Commands involving LUNs should fail.``
 a| 
Erreur de détection de LUN

|===