---
permalink: unix-administration/reference-the-smosmsap-operation-show-command.html 
sidebar: sidebar 
keywords: run, operation, show, command, list, summary, information, output, client, user, snapmanager, host, smsap 
summary: 'Vous pouvez exécuter la commande opération show pour lister les informations récapitulatives de toutes les opérations effectuées sur le profil spécifié. La sortie répertorie l"utilisateur client (l"utilisateur pour l"ordinateur client) et l"utilisateur effectif (l"utilisateur dans SnapManager qui est valide sur l"hôte sélectionné).' 
---
= Commande smsap opération show
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez exécuter la commande opération show pour lister les informations récapitulatives de toutes les opérations effectuées sur le profil spécifié. La sortie répertorie l'utilisateur client (l'utilisateur pour l'ordinateur client) et l'utilisateur effectif (l'utilisateur dans SnapManager qui est valide sur l'hôte sélectionné).



== Syntaxe

[listing, subs="+macros"]
----
pass:quotes[smsap operation show
-profile _profile_name_
[-label _label_ | -id _id_\] [-quiet | -verbose\]]
----


== Paramètres

* `*-profile _profile_name_*`
+
Spécifie le nom du profil. Ce nom peut comporter jusqu'à 30 caractères et doit être unique au sein de l'hôte.

* `*-label _label_*`
+
Spécifie le libellé de l'opération.

* `*-id _id_*`
+
Spécifie l'identifiant de l'opération.

* `*-quiet*`
+
Facultatif : affiche uniquement les messages d'erreur dans la console. La valeur par défaut est d'afficher les messages d'erreur et d'avertissement.

* `*-verbose*`
+
Facultatif : affiche les messages d'erreur, d'avertissement et d'information dans la console.



'''


== Exemple

La ligne de commande suivante affiche des informations détaillées sur une opération :

[listing]
----
smsap operation show -id 8ac861781d0ac992011d0ac999680001  -profile CER
----
[listing]
----
Operation Attempted
    Operation ID: 8ac861781d0ac992011d0ac999680001
    Type:Backup
    For profile: CER
    With Force: No
    Label: 081017180043
    Comments: BRBACKUP
Operation Runtime Information
   Status: SUCCESS
   Start date: 2008-10-16 18:01:00 IST
   End date: 2008-10-17 18:01:26 IST
   Client user: oracle
   Effective user: oracle
   By schedule: none
Host
   Host Run upon: lnx225-248.lab.eng.org.com
   Process ID: 29096
   SnapManager version: 3.3
Repository
   Connection: krishna@smsaprep/10.72.225.155:1521
   Repository version: 62
Error messages
   The operation did not generate any error messages.
Resources in use
   Snapshots:
      f270-225-57:/vol/f270_lnx225_248_10gr2_sap_oracle_cer:smsap_cer_cer1_f_c_2_8ac861781d0ac992011d0ac999680001_0
   Storage components:
    /sapbackup/backCER1.log (File)
    /sapbackup/bdzbalta.anf (File)
    /sapreorg/spaceCER1.log (File)
    /mnt/oracle/CER (File System)
    ...
----
'''