---
permalink: unix-administration/reference-the-smosmsapbackup-restore-command.html 
sidebar: sidebar 
keywords: run, backup, restore, command, database, portion, recover, information, smsap 
summary: 'Vous pouvez exécuter la commande backup restore pour restaurer les sauvegardes d"une base de données ou d"une partie d"une base de données, puis éventuellement récupérer les informations de la base de données.' 
---
= La commande smsap backup restore
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez exécuter le `backup restore` commande permettant de restaurer les sauvegardes d'une base de données ou d'une partie d'une base de données, puis de récupérer éventuellement les informations de la base de données.



== Syntaxe

[listing, subs="+macros"]
----
pass:quotes[smsap backup restore
-profile _profile_name_
[-label _label_ | -id _id_\]
[-files files [_files..._\] |
-tablespaces _tablespaces [tablespaces...\]_\] |
-complete | -controlfiles\]
[-recover {-alllogs | -nologs | -until _until_} [-using-backup-controlfile\] \]
[-restorespec _restorespec_ | -from-secondary [-temp-volume _temp_volume_\] [-copy-id _id_\]\]
[-preview\]
[-fast {-require | -override | -fallback | -off}\]
[-recover-from-location _path1_ [_, path2_\]\] [-taskspec _taskspec_\][-dump\]
[-force\]
[-quiet | -verbose\]]
----


== Paramètres

* `*-profile _profile_name_*`
+
Indique la base de données à restaurer. Le profil contient l'identifiant de la base de données et d'autres informations sur la base de données.

* `*-label _name_*`
+
Restaure la sauvegarde avec l'étiquette spécifiée.

* `*-id _guid_*`
+
Restaure la sauvegarde à l'aide du GUID spécifié. Le GUID est généré par SnapManager lors de la création d'une sauvegarde. Vous pouvez utiliser la commande smsap backup list pour afficher le GUID pour chaque sauvegarde.

* *Choisissez tous les fichiers ou les fichiers spécifiés*
+
Vous pouvez également utiliser l'une des options suivantes :

+
** `-complete` Restaure tous les fichiers de données de la sauvegarde.
** `-tablespaces _list_`: Restaure uniquement les espaces de stockage spécifiés de la sauvegarde.
+
Vous devez utiliser des espaces pour séparer les noms de la liste.

** `-files _list_`: Restaure uniquement les fichiers de données spécifiés à partir de la sauvegarde.
+
Vous devez utiliser des espaces pour séparer les noms de la liste. Si la base de données est en cours d'exécution, SnapManager garantit que l'espace table contenant les fichiers est hors ligne.



* `*-controlfiles*`
+
Restaure les fichiers de contrôle. SnapManager vous permet de restaurer les fichiers de contrôle ainsi que les fichiers de données à partir de sauvegardes en une seule opération. Le `-controlfiles` cette option est indépendante des autres paramètres de l'étendue de restauration, tels que -`complete`, `-tablespaces`, et `-files`.

* `*-recover*`
+
Restaure la base de données après la restauration. Vous devez également spécifier le point auquel SnapManager doit restaurer la base de données à l'aide de l'une des options suivantes :

+
** `-nologs`: Récupère la base de données au moment de la sauvegarde et n'applique aucun journal.
+
Vous pouvez utiliser ce paramètre pour les sauvegardes en ligne ou hors ligne.

** `-alllogs`: Récupère la base de données à la dernière transaction ou à valider et applique tous les journaux requis.
** `-until date`: Récupère la base de données jusqu'à la date et l'heure spécifiées.
+
Vous devez utiliser le format année-mois-date: Heure: Minute: Seconde (_aaaa-mm-jj:hh:mm:ss_). Pour les heures, utilisez le format 12 heures ou 24 heures, selon le paramètre de la base de données.

** `-until scn`: Rolls avance les fichiers de données jusqu'à ce qu'il atteigne le numéro de changement de système spécifié (SCN).
** `-using-backup-controlfile`: Récupère la base de données à l'aide du fichier de contrôle de sauvegarde.


* `*-restorespec*`
+
Vous permet de restaurer les données sur un système de fichiers actif et de les restaurer à partir des données spécifiées en fournissant un mappage de chaque copie Snapshot originale vers son système de fichiers actif. Si vous ne spécifiez pas d'option, SnapManager restaure les données à partir des copies Snapshot sur le stockage primaire. Vous pouvez spécifier l'une des options suivantes :

+
** `-restorespec`: Spécifie les données à restaurer et le format de restauration.
** `-from-secondary`: Restaure les données du stockage secondaire.
+
Vous ne pouvez pas utiliser cette option si la sauvegarde existe sur le stockage primaire ; la sauvegarde primaire doit être libérée avant de pouvoir restaurer une sauvegarde à partir du stockage secondaire. Si vous utilisez un volume temporaire, vous devez spécifier le volume en utilisant le `-temp-volume` option.

+
Vous devez spécifier le `-copy-id` lorsque vous spécifiez le `-from-secondary` option. S'il y a plusieurs sauvegardes sur le système de stockage secondaire, le `-copy-id` permet de spécifier la copie de sauvegarde du stockage secondaire à utiliser pour l'opération de restauration.

+

NOTE: Si vous utilisez Data ONTAP sous 7-mode, vous devez indiquer une valeur valide pour le système `-copy-id` option. Cependant, si vous utilisez clustered Data ONTAP, le `-copy-id` cette option n'est pas requise

+
Lors d'une restauration à partir d'un stockage secondaire, SnapManager procède d'abord à une restauration des données directement depuis le système de stockage secondaire vers le système de stockage primaire (sans impliquer l'hôte). Si SnapManager ne peut pas effectuer ce type de restauration (par exemple, si les fichiers ne font pas partie du système de fichiers), SnapManager revient à une copie de fichier côté hôte. SnapManager propose deux méthodes pour effectuer une restauration de copie de fichier côté hôte à partir d'un stockage secondaire. La méthode sélectionnée par SnapManager est configurée dans `smsap.config` fichier.

** Direct : SnapManager clone les données sur un système de stockage secondaire, monte les données clonées du système de stockage secondaire sur l'hôte, puis copie les données hors du clone dans l'environnement actif.
+
Il s'agit de la stratégie d'accès secondaire par défaut.

** Indirect : SnapManager copie d'abord les données sur un volume temporaire du stockage primaire, monte les données du volume temporaire sur l'hôte, puis copie les données hors du volume temporaire dans l'environnement actif.
+
Cette règle doit être utilisée uniquement si l'hôte ne dispose pas d'un accès direct au système de stockage secondaire. Les restaurations à l'aide de la méthode indirecte prennent deux fois plus de temps que la règle d'accès secondaire direct, car deux copies de ces données sont créées.



+
La décision d'utiliser la méthode directe ou indirecte est contrôlée par la valeur du `_restore.secondaryAccessPolicy_` paramètre dans le `smsap.config` fichier de configuration.

* `*-preview*`
+
Affiche les informations suivantes :

+
** Quel mécanisme de restauration (restauration rapide, restauration du système de fichiers côté stockage, restauration de fichiers côté stockage ou restauration de copie de fichiers côté hôte) sera utilisé pour restaurer chaque fichier
** Pourquoi des mécanismes plus efficaces n'ont pas été utilisés pour restaurer chaque fichier lorsque vous spécifiez le `-verbose` Si vous utilisez le `-preview` vous devez connaître les éléments suivants :
** Le `-force` l'option n'a aucun impact sur la commande.
** Le `-recover` l'option n'a aucun impact sur la commande.
** Le `-fast` option (`-require, -override, -fallback,` ou `-off`) a un impact important sur la production. Pour prévisualiser l'opération de restauration, la base de données doit être montée. Si vous souhaitez prévisualiser un plan de restauration et que la base de données n'est pas actuellement montée, SnapManager monte la base de données. Si la base de données ne peut pas être montée, alors la commande échoue et SnapManager renvoie la base de données à son état d'origine.


+
Le `-preview` permet d'afficher jusqu'à 20 fichiers. Vous pouvez configurer le nombre maximal de fichiers à afficher dans le `smsap.config` fichier.

* `*-fast*`
+
Vous permet de choisir le processus à utiliser dans l'opération de restauration. Vous pouvez forcer SnapManager à utiliser le processus de restauration rapide basé sur les volumes plutôt que d'autres processus de restauration, si toutes les conditions d'éligibilité à la restauration sont remplies. Si vous savez qu'une restauration de volume ne peut pas être effectuée, vous pouvez également utiliser cette procédure pour empêcher SnapManager de réaliser des vérifications d'éligibilité et de restauration à l'aide du processus de restauration rapide.

+
Le `-fast` l'option comprend les paramètres suivants :

+
** `-require`: Vous permet de forcer SnapManager à effectuer une restauration de volume si toutes les conditions d'éligibilité de restauration sont remplies.
+
Si vous spécifiez le `-fast` mais ne spécifiez aucun paramètre pour `-fast`, SnapManager utilise le `-require` paramètre par défaut.

** `-override`: Vous permet de remplacer les vérifications d'éligibilité non obligatoires et d'exécuter le processus de restauration rapide basé sur le volume.
** `-fallback`: Permet de restaurer la base de données à l'aide de toute méthode que SnapManager détermine.
+
Si vous ne spécifiez pas le `-fast` SnapManager utilise la valeur par défaut `backup restore -fast fallback` option.

** `-off`: Vous permet d'éviter le temps nécessaire pour effectuer les vérifications d'admissibilité.


* `*-recover-from-location*`
+
Indique l'emplacement du journal d'archivage externe des fichiers journaux d'archive. SnapManager enregistre les fichiers journaux d'archivage à partir de l'emplacement externe et les utilise pour le processus de restauration.

* `*-taskspec*`
+
Spécifie le fichier XML de spécification de tâche pour l'activité de prétraitement ou de post-traitement de l'opération de restauration. Vous devez fournir le chemin complet du fichier XML de spécification de tâche.

* `*-dump*`
+
Indique de collecter les fichiers de vidage après l'opération de restauration.

* `*-force*`
+
Change l'état de la base de données à un état inférieur à son état actuel, si nécessaire. Pour Real application clusters (RAC), vous devez inclure le `-force` Option si SnapManager doit changer l'état d'une instance RAC à un état inférieur.

+
Par défaut, SnapManager peut indiquer un état plus élevé dans la base de données au cours d'une opération. Cette option n'est pas requise pour que SnapManager change l'état de la base de données à supérieur.

* `*-quiet*`
+
Affiche uniquement les messages d'erreur dans la console. Le paramètre par défaut est d'afficher les messages d'erreur et d'avertissement.

* `*-verbose*`
+
Affiche les messages d'erreur, d'avertissement et d'information dans la console. Vous pouvez utiliser cette option pour voir pourquoi des processus de restauration plus efficaces n'ont pas pu être utilisés pour restaurer le fichier.



'''


== Exemple

L'exemple suivant illustre la restauration d'une base de données avec les fichiers de contrôle :

[listing]
----
smsap backup restore -profile SALES1 -label full_backup_sales_May
-complete -controlfiles -force
----
'''