---
permalink: unix-administration/reference-the-smosmsap-clone-split-delete-command.html 
sidebar: sidebar 
keywords: delete, clone, command, split, operation, cycle, entry, repository, database, smsap, split-delete 
summary: 'Cette commande permet de supprimer une entrée de cycle d"opération de fractionnement de clone d"une base de données de référentiel.' 
---
= La commande smsap clone split-delete
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cette commande permet de supprimer une entrée de cycle d'opération de fractionnement de clone d'une base de données de référentiel.



== Syntaxe

[listing, subs="+macros"]
----
pass:quotes[smsap clone split-delete
-profile _profile_ [-host _hostname_\]
[-label _split-label_ | -id _split-id_\]
[-quiet | -verbose\]]
----


== Paramètres

* `*-profile _profile_*`
+
Spécifie le nom de profil du clone.

* `*-host _hostname_*`
+
Spécifie le nom d'hôte dans lequel le clone existe.

* `*-label _split-label_*`
+
Spécifie le nom d'étiquette généré par le processus de démarrage de la division de clone.

* `*-id _split-id_*`
+
Spécifie l'ID unique généré par le processus de démarrage du fractionnement du clone.

* `*-quiet*`
+
Affiche uniquement les messages d'erreur sur la console. La valeur par défaut est d'afficher les messages d'erreur et d'avertissement.

* `*-verbose*`
+
Affiche des messages d'erreur, d'avertissement et d'information sur la console.


