---
permalink: unix-administration/reference-mounting-a-flexclone-fails-in-nfs-environment.html 
sidebar: sidebar 
keywords: snapmanager, create, flexclone, volume, nfs, environment, export, file, clone, backup, fail, mount, error, message 
summary: 'Lorsque SnapManager crée un FlexClone d"un volume dans un environnement NFS, une entrée est ajoutée au fichier /etc/exports. Le clone ou la sauvegarde ne parvient pas à monter sur un hôte SnapManager et un message d"erreur s"affiche.' 
---
= Le montage d'un volume FlexClone échoue dans un environnement NFS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lorsque SnapManager crée un volume FlexClone dans un environnement NFS, une entrée est ajoutée dans `/etc/exports` fichier. Le clone ou la sauvegarde ne parvient pas à monter sur un hôte SnapManager et un message d'erreur s'affiche.

Le message d'erreur est : `0001-034 Command error: mount failed: mount: filer1:/vol/SnapManager_20090914112850837_vol14 on /opt/NTAPsmsap/mnt/-ora_data02-20090914112850735_1 - WARNING unknown option "zone=vol14" nfs mount: filer1:/vol/SnapManager_20090914112850837_vol14: Permission denied`.

En même temps, le message suivant est généré sur la console du système de stockage : `Mon Sep 14 23:58:37 PDT [filer1: export.auto.update.disabled: warning]: /etc/exports was not updated for vol14 when the vol clone create command was run. Please either manually update /etc/exports or copy /etc/exports.new to it`.

Il est possible que ce message ne soit pas capturé dans les messages AutoSupport.


NOTE: Le clonage de volumes FlexVol sur NFS peut entraîner des problèmes similaires. Vous pouvez suivre les mêmes étapes pour activer le `nfs.export.auto-update` option.

*Que faire*

. Réglez le `nfs.export.auto-update` option `_on_` de sorte que le `/etc/exports` le fichier est mis à jour automatiquement.


`*options nfs.export.auto-update _on_*`


NOTE: Dans la configuration de paires haute disponibilité, assurez-vous que l'option d'exportations NFS est activée pour les deux systèmes de stockage.
