---
permalink: unix-administration/reference-the-smosmsap-schedule-update-command.html 
sidebar: sidebar 
keywords: command, update, schedule, backup, smsap 
summary: 'Cette commande met à jour la planification d"une sauvegarde.' 
---
= La commande smsap schedule update
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cette commande met à jour la planification d'une sauvegarde.



== Syntaxe

[listing, subs="+macros"]
----
pass:quotes[smsap schedule update -profile _profile_name_
-schedule-name _schedule_name_ [-schedule-comment _schedule_comment_\]
-interval {_-hourly_ | _-daily_ | _-weekly_ | _-monthly_ | _-onetimeonly_}
-cronstring _cron_string_  -start-time {_start_time < yyyy-MM-dd HH:mm>_}
-runasuser _runasuser_ [-taskspec _taskspec_\] -force
[-quiet | -verbose\]]
----


== Paramètres

* `*-profile _profile_name_*`
+
Indique le nom du profil associé à la base de données que vous souhaitez planifier la sauvegarde. Le profil contient l'identifiant de la base de données et d'autres informations sur la base de données.

* `*-schedule-name _schedule_name_*`
+
Spécifie le nom que vous fournissez pour le planning.

* `*-schedule-comment _schedule_comment_*`
+
Spécifie un commentaire facultatif décrivant la planification de la sauvegarde.

* `*-interval { -hourly | -daily | -weekly | -monthly | -onetimeonly}*`
+
Indique l'intervalle de temps par lequel les sauvegardes sont créées. Vous pouvez planifier la sauvegarde toutes les heures, tous les jours, toutes les semaines, tous les mois ou une seule fois.

* `*-cronstring _cron_string_*`
+
Spécifie pour planifier la sauvegarde à l'aide de cronstring. Les expressions cron sont utilisées pour configurer des instances de CronTrigger. Les expressions cron sont des chaînes qui sont en fait composés de sept sous-expressions :

+
** 1 correspond aux secondes
** 2 correspond aux minutes
** 3 correspond aux heures
** 4 correspond à un jour dans un mois
** 5 correspond au mois
** 6 correspond à un jour dans une semaine
** 7 correspond à l'année (facultatif)


* `*-start-time yyyy-MM-dd HH:mm*`
+
Spécifie l'heure de début de l'opération de planification. L'heure de début de l'horaire doit être incluse au format aaaa-MM-jj HH:mm.

* `*-runasuser _runasuser_*`
+
Indique de modifier l'utilisateur de l'opération de sauvegarde planifiée pendant la planification de la sauvegarde.

* `*-taskspec _taskspec_*`
+
Spécifie le fichier XML de spécification de tâche qui peut être utilisé pour l'activité de prétraitement ou de post-traitement de l'opération de sauvegarde. Le chemin complet du fichier XML devrait être fourni avec l'option -taskspspspspspspspspspspspec.


