---
permalink: unix-administration/reference-the-smosmsap-history-list-command.html 
sidebar: sidebar 
keywords: command, enable, view, list, history, details, snapmanager, operation, smsap 
summary: 'Cette commande vous permet d"afficher une liste des détails de l"historique de l"opération SnapManager.' 
---
= La commande smsap History list
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cette commande vous permet d'afficher une liste des détails de l'historique de l'opération SnapManager.



== Syntaxe

[listing, subs="+macros"]
----
pass:quotes[smsap history list
-profile {-name _profile_name_ [_profile_name1, profile_name2_\] | -all
-repository -login [-password _repo_password_\] -username _repo_username_
-host _repo_host_
-dbname _repo_dbname_
-port _repo_port_}
-operation {-operations _operation_name_ [_operation_name1, operation_name2_\] | -all}
[-delimiter _character_\] [-quiet | -verbose\]]
----


== Paramètres

* `*-profile _profile_*`
+
Spécifie le nom du profil. Ce nom peut comporter jusqu'à 30 caractères et doit être unique au sein de l'hôte.

* `*_-repository_*`
+
Les options suivantes -repository spécifient les détails de la base de données qui stocke le profil.

* `*-dbname _repo_dbname_*`
+
Indique le nom de la base de données qui stocke le profil. Utilisez le nom global ou le SID.

* `*-host _repo_host_*`
+
Indique le nom ou l'adresse IP de l'ordinateur hôte sur lequel s'exécute la base de données de référentiel.

* `*-login*`
+
Démarre les détails de connexion au référentiel.

* `*-username _repo_username_*`
+
Indique le nom d'utilisateur nécessaire pour accéder à la base de données qui stocke le référentiel.

* `*-port _repo_port_*`
+
Spécifie le numéro de port TCP utilisé pour accéder à la base de données qui stocke le référentiel.

* `*-operation {-operations _operation_name_ [_operation_name1, operation_name2_] | -all*`
+
Spécifie l'opération SnapManager pour laquelle vous configurez l'historique.

* `*-quiet*`
+
Affiche uniquement les messages d'erreur sur la console. La valeur par défaut est d'afficher les messages d'erreur et d'avertissement.

* `*-verbose*`
+
Affiche des messages d'erreur, d'avertissement et d'information sur la console.



'''


== Exemple de commande

[listing]
----
 smsap history list -profile -name PROFILE1 -operation -operations backup -verbose
----
'''