---
permalink: unix-administration/reference-the-smosmsap-repository-rollingback-command.html 
sidebar: sidebar 
keywords: command, enable, roll, back, revert, version, snapmanager, original, version, upgrade, smsap, repository, rollback 
summary: 'Cette commande vous permet de restaurer ou de revenir à une version supérieure de SnapManager vers la version d"origine à partir de laquelle vous avez mis à niveau.' 
---
= La commande smsap repository rollback
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cette commande vous permet de restaurer ou de revenir à une version supérieure de SnapManager vers la version d'origine à partir de laquelle vous avez mis à niveau.



== Syntaxe

[listing, subs="+macros"]
----
pass:quotes[smsap repository rollback
-repository
-dbname _repo_service_name_
-host _repo_host_
-login -username _repo_username_
-port _repo_port_
-rollbackhost _host_with_target_database_
[-force]]
[-quiet | -verbose]
----


== Paramètres

* `*-repository*`
+
Les options suivantes -repository spécifient les détails de la base de données pour le référentiel.

* `*-dbname _repo_service_name_*`
+
Indique le nom de la base de données qui stocke le référentiel. Utilisez le nom global ou le SID.

* `*-host _repo_host_*`
+
Indique le nom ou l'adresse IP de l'ordinateur hôte sur lequel s'exécute la base de données de référentiel.

* `*-login*`
+
Démarre les détails de connexion au référentiel.

* `*-username _repo_username_*`
+
Indique le nom d'utilisateur nécessaire pour accéder à la base de données qui stocke le référentiel.

* `*-rollbackhost _host_with_target_database_*`
+
Spécifie le nom de l'hôte qui sera restauré à partir d'une version supérieure de SnapManager vers la version inférieure d'origine.

* `*-port _repo_port_*`
+
Spécifie le numéro de port TCP utilisé pour accéder à la base de données qui stocke le référentiel.

* `*-force*`
+
Tente de forcer la mise à jour du référentiel. SnapManager vous invite à effectuer une sauvegarde du référentiel actuel avant la mise à jour.

* `*-noprompt*`
+
N'affiche pas l'invite avant la mise à jour de la base de données du référentiel. L'option -noprompt permet de s'assurer que l'invite n'apparaît pas, ce qui facilite la mise à jour des référentiels à l'aide d'un script.

* `*-quiet*`
+
Affiche uniquement les messages d'erreur sur la console. La valeur par défaut est d'afficher les messages d'erreur et d'avertissement.

* `*-verbose*`
+
Affiche des messages d'erreur, d'avertissement et d'information sur la console.



'''


== Exemple de commande

L'exemple suivant met à jour le référentiel dans la base de données SALESDB.

[listing]
----
smsap repository rollback -repository -dbname SALESDB
-host server1 -login -username admin -port 1521 -rollbackhost hostA
----
'''