---
permalink: unix-administration/reference-the-smosmsapbackup-verify-command.html 
sidebar: sidebar 
keywords: run, backup, verify, command, oracle, smsap 
summary: Vous pouvez exécuter la commande backup verify pour vérifier si la sauvegarde est dans un format valide pour Oracle. 
---
= La commande smsap backup verify
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez exécuter le `backup verify` Commande pour vérifier si la sauvegarde est dans un format valide pour Oracle.



== Syntaxe

[listing, subs="+macros"]
----
pass:quotes[smsap backup verify
-profile _profile_name_
[-label _backup_name- | [-id _guid_\]
[-retain {-hourly | -daily | -weekly | -monthly | -unlimited}\] [-force\]
[-dump\] [-quiet | -verbose\]]
----


== Paramètres

* ``*-profile _profile_name_*``
+
Spécifie le profil pour lequel vous souhaitez vérifier une sauvegarde. Le profil contient l'identifiant de la base de données et d'autres informations sur la base de données.

* ``*-id _guid_*``
+
Vérifie la sauvegarde à l'aide du GUID spécifié. Le GUID est généré par SnapManager lors de la création d'une sauvegarde. Vous pouvez utiliser la commande smsap backup list pour afficher le GUID pour chaque sauvegarde.

* ``*-label _label_name_*``
+
Vérifie la sauvegarde avec l'étiquette spécifiée.

* ``*-dump*``
+
Collecte les fichiers de vidage après l'opération de vérification de la sauvegarde réussie ou ayant échoué.

* ``*-force*``
+
Force la base de données à l'état nécessaire pour effectuer l'opération de vérification.

* ``*-quiet*``
+
Affiche uniquement les messages d'erreur dans la console. La valeur par défaut est d'afficher les messages d'erreur et d'avertissement.

* ``*-verbose*``
+
Affiche les messages d'erreur, d'avertissement et d'information dans la console.



'''


== Exemple

Voici un exemple de vérification de la sauvegarde :

[listing]
----
smsap backup verify -profile SALES1 -label full_backup_sales_May -quiet
----
[listing]
----
DBVERIFY - Verification starting : FILE = +SMSAP_1_1161675083835/smsmsap/datafile/data.277.582482539 ...
----
'''