---
permalink: unix-administration/reference-the-smosmsap-password-reset-command.html 
sidebar: sidebar 
keywords: run, password, reset, command, profile, smsap 
summary: 'Vous pouvez exécuter la commande de réinitialisation de mot de passe pour réinitialiser le mot de passe d"un profil.' 
---
= La commande smsap password reset
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez exécuter la commande de réinitialisation de mot de passe pour réinitialiser le mot de passe d'un profil.



== Syntaxe

[listing, subs="+macros"]
----
pass:quotes[smsap password reset
-profile _profile_ [-profile-password _profile_password_\]
[-repository-hostadmin-password _repository_hostadmin_password_\]
[-quiet | -verbose]]
----


== Paramètres

* `*-profile _profile_*`
+
Indique le nom du profil pour lequel vous souhaitez réinitialiser le mot de passe.

* `*-profile-password _profile_password_*`
+
Spécifie le nouveau mot de passe pour le profil.

* `*-repository-hostadmin-password _admin_password_*`
+
Spécifie les informations d'identification utilisateur autorisées avec privilèges root pour la base de données du référentiel.

* `*-quiet*`
+
Affiche uniquement les messages d'erreur dans la console. La valeur par défaut est d'afficher les messages d'erreur et d'avertissement.

* `*-verbose*`
+
Affiche les messages d'erreur, d'avertissement et d'information dans la console.


