---
permalink: unix-administration/reference-the-smosmsap-clone-split-command.html 
sidebar: sidebar 
keywords: run, clone, split, command, independent, original, snapmanager, smsap, operation, profile 
summary: 'Vous pouvez exécuter la commande clone Split pour séparer un clone. Le clone fractionné devient indépendant du clone d"origine. SnapManager génère un nouveau profil après l"opération de fractionnement de clone et vous pouvez utiliser ce profil pour gérer le clone divisé.' 
---
= La commande smsap clone split
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez exécuter le `clone split` commande permettant de séparer un clone. Le clone fractionné devient indépendant du clone d'origine. SnapManager génère un nouveau profil après l'opération de fractionnement de clone et vous pouvez utiliser ce profil pour gérer le clone divisé.



== Syntaxe

[listing, subs="+macros"]
----
pass:quotes[smsap clone split
-profile _clone-profile_
[-host hostname\]
{-label _clone-label_ | -id _clone-id_} [-split-label _split-operation_label_\]
[-comment _comment_\]
-new-profile _new-profile-name_ [-profile-password _new-profile_password_\]
-repository -dbname _repo_service_name_
-host _repo_host_
-port _repo_port_
-login -username _repo_username_
-database -dbname _db_dbname_
-host _db_host_ [-sid _db_sid_\] [-login -username _db_username_ -password _db_password_
-port _db_port_\]
[-rman {{-controlfile | {-login -username _rman_username_
-password _rman_password_} -tnsname _rman_tnsname_}}\]
-osaccount _osaccount_
-osgroup _osgroup_
[-retain
[-hourly [-count _n_\] [-duration  _m_\]\]
[-daily [-count _n_\] [-duration _m_\]\]
[-weekly  [-count _n_\] [-duration _m_\]\]
[-monthly [-count _n_\] [-duration _m_\]\] \]
[-profile-comment _profile-comment_\]
[-snapname-pattern _pattern_\]
[-protect [-protection-policy _policy_name_\]\] | [-noprotect\]\]
[-summary-notification
[-notification
[-success -email _email_address1,email_address2_
-subject subject-pattern\]
[failure -email _email_address1,email_address2_
-subject _subject-pattern_\] \]
[-separate-archivelog-backups
-retain-archivelog-backups -hours  _hours_ |
-days _days_ |
-weeks _weeks_ |
-months _months_
[-protect [-protection-policy _policy_name_ | -noprotect\]
[-include-with-online-backups | -no-include-with-online-backups\]\]
[-dump\]
[-quiet | -verbose\]]
----


== Paramètres

* `*-profile _clone-profile_*`
+
Spécifie le nom de profil à partir duquel le clone est créé.

* `*-host _hostname_*`
+
Spécifie le nom d'hôte dans lequel le clone existe.

* `*label _clone-label_*`
+
Spécifie le nom de libellé généré par l'opération de clonage.

* `*-id _clone-id_*`
+
Spécifie l'ID unique généré par l'opération de clonage.

* `*-split-label split-_operation_label_*`
+
Spécifie le nom de libellé généré par l'opération de clonage.

* `*-new-profile _new-profile_name_*`
+
Spécifie le nouveau nom de profil que SnapManager va générer après une opération de fractionnement réussie.

* `*-profile-password _new-profile_password_*`
+
Spécifie le mot de passe du profil.

* `*-repository*`
+
Spécifie les détails de la base de données pour le référentiel.

* `*-dbname _repo_service_name_*`
+
Indique le nom de la base de données qui stocke le référentiel. Vous pouvez utiliser le nom global ou l'identifiant système.

* `*-host _repo_host_*`
+
Indique le nom ou l'adresse IP de l'ordinateur hôte sur lequel réside la base de données du référentiel.

* `*-port _repo_port_*`
+
Spécifie le numéro de port TCP (transmission Control Protocol) utilisé pour accéder à l'hôte sur lequel réside la base de données de référentiel.

* `*-login*`
+
Spécifie les détails de connexion au référentiel. Cette option est facultative. Si ce n'est pas le cas, SnapManager utilise par défaut le mode de connexion à l'authentification OS.

* `*-username _repo_username_*`
+
Indique le nom d'utilisateur requis pour accéder à l'hôte sur lequel réside la base de données du référentiel.

* `*-database*`
+
Spécifie les détails de la base de données qui sera sauvegardée, restaurée ou clonée.

* `*-dbname _db_dbname_*`
+
Indique le nom de la base de données décrit par le profil. Vous pouvez utiliser le nom global ou l'identifiant système.

* `*-host _db_host_*`
+
Indique le nom ou l'adresse IP de l'ordinateur hôte sur lequel réside la base de données.

* `*-sid _db_sid_*`
+
Indique l'identifiant système de la base de données décrit par le profil. Par défaut, SnapManager utilise le nom de la base de données comme identificateur système. Si l'identificateur système est différent du nom de la base de données, vous devez le spécifier à l'aide de l' `-sid` option.

* `*-login*`
+
Spécifie les détails de connexion à la base de données.

* `*-username _db_username_*`
+
Indique le nom d'utilisateur requis pour accéder à la base de données décrit par le profil.

* `*-password _db_password_*`
+
Spécifie le mot de passe requis pour accéder à la base de données décrit par le profil.

* `*-osaccount _osaccount_*`
+
Spécifie le nom du compte utilisateur de la base de données Oracle. SnapManager utilise ce compte pour effectuer les opérations Oracle telles que le démarrage et l'arrêt. Il s'agit généralement de l'utilisateur qui possède le logiciel Oracle sur l'hôte, par exemple, orasid.

* `*-osgroup _osgroup_*`
+
Spécifie le nom du groupe de bases de données Oracle associé au compte orasID.

+

NOTE: Le `-osaccount` et `-osgroup` Les variables sont requises pour UNIX mais ne sont pas autorisées pour les bases de données fonctionnant sous Windows.

* `*-retain [-hourly [-count n] [-duration m]] [-daily [-count n] [-duration m]] [-weekly [-count n] [-duration m]] [-monthly [-count n] [-duration m]]*`
+
Spécifie la stratégie de rétention pour une sauvegarde.

+
Pour chaque classe de rétention, le nombre de rétention ou la durée de conservation peuvent être spécifiés. La durée est exprimée en unités de la classe (par exemple, heures pour l'heure, jours pour la journée). Par exemple, si vous spécifiez uniquement une durée de conservation de 7 pour les sauvegardes quotidiennes, SnapManager ne limite pas le nombre de sauvegardes quotidiennes du profil (car le nombre de rétention est 0), mais SnapManager supprimera automatiquement les sauvegardes quotidiennes créées il y a plus de 7 jours.

* `*-profile-comment _profile-comment_*`
+
Spécifie le commentaire d'un profil décrivant le domaine de profil.

* `*-snapname-pattern _pattern_*`
+
Spécifie le modèle de nom pour les copies Snapshot. Vous pouvez également inclure du texte personnalisé, par exemple HAOPS pour les opérations hautement disponibles, dans tous les noms de copie Snapshot. Vous pouvez modifier le schéma de nommage des copies Snapshot lorsque vous créez un profil ou après sa création. La mise à jour s'applique uniquement aux copies Snapshot qui n'ont pas encore été créées. Les copies Snapshot qui existent conservent le modèle Snapname précédent. Vous pouvez utiliser plusieurs variables dans le texte du motif.

* `*-protect -protection-policy _policy_name_*`
+
Indique si la sauvegarde doit être protégée sur le stockage secondaire.

+

NOTE: Si `-protect` est spécifié sans `-protection-policy`, le dataset ne dispose alors pas d'une règle de protection. Si `-protect` est spécifié et `-protection-policy` n'est pas défini lorsque le profil est créé, il peut être défini ultérieurement par le `smsap profile update` Contrôlez ou définissez par l'administrateur du stockage à l'aide de la console protection Manager.

* `*-summary-notification*`
+
Spécifie les détails de la configuration de la notification par e-mail de synthèse pour plusieurs profils sous une base de données de référentiel. SnapManager génère cet e-mail.

* `*-notification*`
+
Spécifie les détails de la configuration de la notification par e-mail pour le nouveau profil. SnapManager génère cet e-mail. La notification par e-mail permet à l'administrateur de base de données de recevoir des e-mails sur l'état réussi ou échoué de l'opération de base de données effectuée à l'aide de ce profil.

* `*-success*`
+
Indique que la notification par e-mail est activée pour un profil pour lequel l'opération SnapManager réussit.

* `*-email _email address 1 email address 2_*`
+
Spécifie l'adresse e-mail du destinataire.

* `*-subject _subject-pattern_*`
+
Spécifie l'objet de l'e-mail.

* `*-failure*`
+
Indique que la notification par e-mail est activée pour un profil lorsque l'opération SnapManager échoue.

* `*-separate-archivelog-backups*`
+
Spécifie que la sauvegarde du journal d'archivage est séparée de la sauvegarde du fichier de données. Il s'agit d'un paramètre facultatif que vous pouvez fournir lors de la création du profil. Une fois les sauvegardes séparées à l'aide de cette option, vous pouvez créer une sauvegarde des fichiers de données uniquement ou une sauvegarde des journaux d'archivage uniquement.

* `*-retain-archivelog-backups -hours _hours_ | -days _days_ | -weeks _weeks_| -months _months_*`
+
Indique que les sauvegardes du journal d'archivage sont conservées en fonction de la durée de conservation du journal d'archivage (horaire, quotidien, hebdomadaire ou mensuel).

* `*protect [-protection-policy _policy_name_] | -noprotect*`
+
Indique que les fichiers journaux d'archives sont protégés en fonction de la stratégie de protection du journal d'archivage.

+
Indique que les fichiers journaux d'archives ne sont pas protégés à l'aide de l' `-noprotect` option.

* `*-include-with-online-backups | -no-include-with-online-backups*`
+
Indique que la sauvegarde du journal d'archivage est incluse avec la sauvegarde de base de données en ligne.

+
Indique que les sauvegardes du journal d'archivage ne sont pas incluses avec la sauvegarde de base de données en ligne.

* `*-dump*`
+
Indique que les fichiers de vidage ne sont pas collectés après l'opération de création de profil réussie.

* `*-quiet*`
+
Affiche uniquement les messages d'erreur dans la console. Le paramètre par défaut affiche des messages d'erreur et d'avertissement.

* `*-verbose*`
+
Affiche les messages d'erreur, d'avertissement et d'information dans la console.


