---
permalink: unix-administration/reference-troubleshooting-storage-system-renaming-issue.html 
sidebar: sidebar 
keywords: face, issue, renaming, rename, storage, system, successful, troubleshooting 
summary: 'Vous pouvez être confronté à des problèmes lors de la modification du nom d"un système de stockage ou après l"avoir renommé du système de stockage.' 
---
= Dépannage du problème de changement de nom du système de stockage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez être confronté à des problèmes lors de la modification du nom d'un système de stockage ou après l'avoir renommé du système de stockage.

Lorsque vous tentez de renommer le système de stockage, l'opération peut échouer avec le message d'erreur suivant : `SMSAP-05085 No storage controller "fas3020-rtp07New" is found to be associated with the profile`

Vous devez saisir l'adresse IP ou le nom du système de stockage qui est indiqué lors de l'exécution du système `smsap storage list` commande.

Après avoir renommé le système de stockage, les opérations de SnapManager peuvent échouer si SnapManager ne reconnaît pas le système de stockage. Pour résoudre ce problème, vous devez effectuer quelques étapes supplémentaires sur l'hôte du serveur DataFabric Manager et sur l'hôte du serveur SnapManager.

Effectuez les opérations suivantes sur l'hôte du serveur DataFabric Manager :

. Supprimez l'adresse IP et l'hôte du système de stockage précédent dans le fichier hôte situé à ``/etc/hosts`` Dans l'hôte du serveur DataFabric Manager.
. Ajoutez la nouvelle adresse IP et l'hôte du nouveau système de stockage dans le fichier hôte situé à ``/etc/hosts`` Dans l'hôte du serveur DataFabric Manager.
. Modifiez le nom d'hôte de stockage en entrant la commande suivante :
+
`*dfm host rename -a _old_host_namenew_host_name_*`

. Définissez la nouvelle adresse IP dans l'hôte en entrant la commande suivante :
+
`*dfm host set _old_host_name_or_objId_ hostPrimaryAddress = _new_storage_controller_ip_address_*`

+

NOTE: Vous devez effectuer cette étape uniquement si vous avez spécifié l'adresse IP comme nouveau nom de système de stockage.

. Mettez à jour le nouveau nom du système de stockage dans l'hôte du serveur DataFabric Manager en entrant la commande suivante :
+
`*dfm host diag _old_storage_name_*`

+
Vous pouvez vérifier que l'ancien nom de contrôleur de stockage est remplacé par le nouveau nom de contrôleur de stockage en entrant la commande suivante :

+
`*dfm host discover new_storage_name*`



Procédez comme suit en tant qu'utilisateur root dans l'hôte du serveur SnapManager.


NOTE: Lorsque vous saisissez le nom du nouveau contrôleur de stockage, assurez-vous d'utiliser le nom d'alias du système et non le nom de domaine complet (FQDN).

. Supprimez l'ancien nom de système de stockage en entrant la commande suivante :
+
`*snapdrive config delete _old_storage_name_*`

+

NOTE: Si vous ne supprimez pas le nom de l'ancien système de stockage, toutes les opérations de SnapManager échouent.

. Supprimez l'adresse IP et l'hôte du système de stockage précédent dans le fichier hôte situé à `etc/hosts` dans l'hôte de base de données cible.
. Ajoutez la nouvelle adresse IP et l'hôte du nouveau système de stockage dans le fichier hôte situé à ``/etc/hosts`` dans l'hôte de base de données cible.
. Ajoutez le nouveau nom de système de stockage en entrant la commande suivante :
+
`*snapdrive config set root _new_storage_name_*`

. Mapper les noms de système de stockage précédents et ultérieurs en entrant la commande suivante :
+
`*snapdrive config migrate set _old_storage_namenew_storage_name_*`

. Supprimez le chemin de gestion de l'ancien système de stockage en entrant la commande suivante :
+
``*snapdrive config delete -mgmtpath _old_storage_name_*``

. Ajoutez le chemin de gestion du nouveau système de stockage en entrant la commande suivante :
+
`*snapdrive config set -mgmtpath _new_storage_name_*`

. Mettez à jour le jeu de données des fichiers de données et des fichiers journaux d'archivage avec le nouveau nom du système de stockage en entrant la commande suivante :
+
`*snapdrive dataset changehostname -dn _dataset_name_ -oldname _old_storage_name_ -newname _new_storage_name_*`

. Mettez à jour le profil du nouveau système de stockage en entrant la commande suivante :
+
`*smsap storage rename -profile _profile_name_ -oldname _old_storage_name_ -newname _new_storage_name_*`

. Vérifiez le système de stockage associé au profil en saisissant la commande suivante :
+
`*smsap storage list -profile _profile_name_*`


