---
permalink: unix-administration/reference-the-smosmsap-repository-rollingupgrade.html 
sidebar: sidebar 
keywords: command, perform, roll, upgrade, single, host, multiple, associate, target, database, version, snapmanager, smsap, repository, rollingupgrade 
summary: 'Cette commande effectue le déploiement d"une mise à niveau sur un ou plusieurs hôtes uniques et leurs bases de données cibles associées à partir d"une version inférieure d"SnapManager vers une version supérieure. L"hôte mis à niveau est géré uniquement avec la version supérieure de SnapManager.' 
---
= La commande smsap repository rollingupgrade
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cette commande effectue le déploiement d'une mise à niveau sur un ou plusieurs hôtes uniques et leurs bases de données cibles associées à partir d'une version inférieure d'SnapManager vers une version supérieure. L'hôte mis à niveau est géré uniquement avec la version supérieure de SnapManager.



== Syntaxe

[listing, subs="+macros"]
----
pass:quotes[smsap repository rollingupgrade
-repository
-dbname _repo_service_name_
-host _repo_host_
-login -username _repo_username_
-port _repo_port_
-upgradehost _host_with_target_database_
[-force] [-noprompt]
[-quiet | -verbose]
----


== Paramètres

* `*-repository*`
+
Les options suivantes -repository spécifient les détails de la base de données pour le référentiel.

* `*-dbname _repo_service_name_*`
+
Indique le nom de la base de données qui stocke le référentiel. Utilisez le nom global ou le SID.

* `*-host _repo_host_*`
+
Indique le nom ou l'adresse IP de l'ordinateur hôte sur lequel s'exécute la base de données de référentiel.

* `*-login*`
+
Démarre les détails de connexion au référentiel.

* `*-username _repo_username_*`
+
Indique le nom d'utilisateur nécessaire pour accéder à la base de données qui stocke le référentiel.

* `*-upgradehost _host_with_target_database_*`
+
Spécifie le nom de l'hôte qui sera mis à niveau d'une version inférieure de SnapManager vers une version supérieure.

* `*-port _repo_port_*`
+
Spécifie le numéro de port TCP utilisé pour accéder à la base de données qui stocke le référentiel.

* `*-force*`
+
Tente de forcer la mise à jour du référentiel. SnapManager vous invite à effectuer une sauvegarde du référentiel actuel avant la mise à jour.

* `*-noprompt*`
+
N'affiche pas l'invite avant la mise à jour de la base de données du référentiel. À l'aide du `-noprompt` permet de s'assurer que l'invite ne s'affiche pas, ce qui facilite la mise à jour des référentiels à l'aide d'un script.

* `*-quiet*`
+
Affiche uniquement les messages d'erreur sur la console. La valeur par défaut est d'afficher les messages d'erreur et d'avertissement.

* `*-verbose*`
+
Affiche des messages d'erreur, d'avertissement et d'information sur la console.



'''


== Exemple de commande

L'exemple suivant met à jour le référentiel dans la base de données SALESDB.

[listing]
----
smsap repository rollingupgrade -repository -dbname SALESDB
-host server1 -login -username admin -port 1521 -upgradehost hostA
----
'''