---
permalink: unix-administration/reference-the-smosmsapoperation-list-command.html 
sidebar: sidebar 
keywords: command, list, summary, information, operation, profile, smsap 
summary: Cette commande répertorie les informations récapitulatives de toutes les opérations enregistrées sur un profil spécifié. 
---
= La commande smsap operation list
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cette commande répertorie les informations récapitulatives de toutes les opérations enregistrées sur un profil spécifié.



== Syntaxe

[listing, subs="+macros"]
----
pass:quotes[smsap operation list
-profile _profile_name_
[-delimiter _character_]]
[-quiet | -verbose]]
----


== Paramètres

* `*-profile _profile_name_*`
+
Spécifie le nom du profil. Ce nom peut comporter jusqu'à 30 caractères et doit être unique au sein de l'hôte.

* `*-delimiter _character_*`
+
(Facultatif) lorsque ce paramètre est spécifié, la commande répertorie chaque ligne d'une ligne distincte et les attributs de cette ligne sont séparés par le caractère spécifié.

* ``*-quiet*``
+
(Facultatif) affiche uniquement les messages d'erreur sur la console. La valeur par défaut est d'afficher les messages d'erreur et d'avertissement.

* ``*-verbose*``
+
(Facultatif) affiche des messages d'erreur, d'avertissement et d'information sur la console.



'''


== Exemple de commande

L'exemple suivant répertorie les informations récapitulatives de toutes les opérations consignées sur le profil spécifié.

[listing]
----
smsap operation list -profile myprofile
----
[listing]
----
Start Date Status Operation ID Type Host
-------------------- ---------- -------------------------------- ------------------ --
2007-07-16 16:03:57 SUCCESS 8abc01c813d0a1530113d0a15c5f0005 Profile Create Host3
2007-07-16 16:04:55 FAILED 8abc01c813d0a2370113d0a241230001 Backup Host3
2007-07-16 16:50:56 SUCCESS 8abc01c813d0cc580113d0cc60ad0001 Profile Update Host3
2007-07-30 15:44:30 SUCCESS 8abc01c81418a88e011418a8973e0001 Remove Backup Host3
2007-08-10 14:31:27 SUCCESS 8abc01c814510ba20114510bac320001 Backup Host3
2007-08-10 14:34:43 SUCCESS 8abc01c814510e9f0114510ea98f0001 Mount Host3
2007-08-10 14:51:59 SUCCESS 8abc01c814511e6e0114511e78d40001 Unmount Host3
----
'''