---
permalink: unix-administration/task-use-protection-manager-to-configure-secondary-backup-schedules.html 
sidebar: sidebar 
keywords: support, backup, database, secondary, storage, administrator, protection, manager, configure, schedule 
summary: 'Pour prendre en charge la sauvegarde de la base de données sur du stockage secondaire, l"administrateur du stockage utilise protection Manager afin de configurer un programme de sauvegarde.' 
---
= Utilisez protection Manager pour configurer les planifications de sauvegarde secondaires
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour prendre en charge la sauvegarde de la base de données sur du stockage secondaire, l'administrateur du stockage utilise protection Manager afin de configurer un programme de sauvegarde.

*Ce dont vous aurez besoin*

Avant de configurer la planification de sauvegardes secondaires, l'administrateur du stockage confère au partenaire DBA les informations suivantes :

* Planification que l'administrateur de base de données souhaite suivre pour les sauvegardes secondaires
+
Dans ce cas, les sauvegardes une fois par jour sont effectuées à 7 h Les sauvegardes hebdomadaires sont également exécutées le samedi à 1 h



.Étapes
. Accédez à la console de gestion NetApp de protection Manager.
. Dans la barre de menus, cliquez sur *stratégies* > *protection* > *horaires*.
+
L'onglet programmes de la fenêtre stratégies de protection s'affiche.

. Sélectionnez l'horaire quotidien** chaque jour à 8:00 PM** dans la liste des horaires.
. Cliquez sur *Copier*.
+
Un nouvel horaire quotidien, *copie du quotidien à 8:00 PM*, est affiché dans la liste. Elle est déjà sélectionnée.

. Cliquez sur *Modifier*.
+
La feuille de propriétés Modifier horaire quotidien s'ouvre sur l'onglet horaire.

. Modifiez le nom de l'horaire sur *Payroll Daily à 7 PM*, mettez à jour la description, puis cliquez sur *Apply*.
+
Vos modifications sont enregistrées.

. Cliquez sur l'onglet *événements quotidiens*.
+
L'heure de sauvegarde quotidienne actuelle de la planification est de 8:00 s'affiche.

. Cliquez sur *Ajouter* et saisissez *7:00 PM* dans le nouveau champ heure, puis cliquez sur *appliquer*.
+
L'heure de sauvegarde quotidienne actuelle de l'agenda est maintenant de 7:00

. Cliquez sur *OK* pour enregistrer vos modifications et quitter la feuille de propriétés.
+
Votre nouvel horaire quotidien, *paie quotidienne à 7 h*, est affiché dans la liste des horaires.

. Sélectionnez l'horaire hebdomadaire** dimanche à 8:00 PM plus tous les jours** dans la liste des horaires.
. Cliquez sur *Copier*.
+
Un nouvel horaire hebdomadaire, *copie du dimanche à 8:00 PM plus quotidien*, est affiché dans la liste. Elle est déjà sélectionnée.

. Cliquez sur *Modifier*.
+
La feuille de propriétés Modifier horaire hebdomadaire s'ouvre sur l'onglet planification.

. Modifiez le nom de l'horaire à *Payroll Saturday à 1 h plus quotidiennement à 7 h* et mettez à jour la description.
. Dans la liste déroulante *horaire quotidien*, sélectionnez l'horaire quotidien que vous venez de créer, *paie quotidienne à 7 h*.
+
La sélection de *Payroll Daily à 7 PM* signifie que ce calendrier définit le moment où les opérations quotidiennes se produisent lorsque le *Payroll Saturday à 1 h plus quotidien à 7 h* calendrier est appliqué à une police.

. Cliquez sur *OK* pour enregistrer vos modifications et quitter la feuille de propriétés.
+
Votre nouvel horaire hebdomadaire, *paie le samedi à 1 h plus tous les jours à 7 h*, est affiché dans la liste des horaires.


