---
permalink: unix-administration/task-split-a-clone-on-a-primary-or-secondary-storage.html 
sidebar: sidebar 
keywords: clone, split, complete, metadata, remove, repository, primary, secondary, storage, delete, free 
summary: Vous pouvez utiliser la commande clone Split pour séparer le clone. Une fois le partage de clone terminé, les métadonnées de clone sont supprimées de la base de données du référentiel et la sauvegarde associée au clone peut être supprimée ou libérée. 
---
= Séparer un clone sur un système de stockage primaire ou secondaire
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `clone split` commande permettant de séparer le clone. Une fois le partage de clone terminé, les métadonnées de clone sont supprimées de la base de données du référentiel et la sauvegarde associée au clone peut être supprimée ou libérée.

*À propos de cette tâche*

Le nouveau profil créé après l'opération de fractionnement réussie est utilisé pour gérer le clone fractionné. Le nouveau profil sera similaire à tout autre profil existant dans SnapManager. Vous pouvez utiliser ce profil pour effectuer des opérations de sauvegarde, de restauration et de clonage.

En outre, vous pouvez également configurer les notifications par e-mail pour le nouveau profil. Cela permet à l'administrateur de base de données d'être averti de l'état de l'opération de base de données effectuée à l'aide du profil.


NOTE: SnapManager prend en charge l'opération de fractionnement lorsqu'elle est effectuée sur un FlexClone uniquement.

Si l'opération de fractionnement échoue, un message d'erreur approprié avec la raison de l'échec s'affiche. L'état de plusieurs opérations est également affiché dans le journal des opérations. Par exemple :

[listing]
----
--[ INFO] The following operations were completed:
Clone Split : Success
Profile Create : Failed
Clone Detach : Success
----
Vous pouvez éventuellement collecter les fichiers de dump après une opération de fractionnement de clone réussie ou ayant échoué.


NOTE: Une fois que vous avez saisi le `clone split` Vous ne devez pas arrêter le serveur SnapManager tant que l'opération de fractionnement du clone n'a pas démarré.


NOTE: SnapManager génère le profil même si vous ne fournissez aucune valeur pour le compte Oracle (osaccount et osgroup).

.Étape
. Saisissez la commande suivante :
+
`*smsap clone split -profile _clone-profile_ -host _hostname_ [-label _clone-label_ | -id _clone-id_]-split-label _split-operation-label_ -comment _comment_ new-profile _new-profile-name_ [-profile-password _new-profile_password_] -repository -dbname _repo_service_name_ -host _repo_host_ -port _repo_port_ -login-username _repo_username_ -database -dbname _db_dbname_ -host _db_host_ [-siddb_sid] [-login-username _db_username_ -password _db_password_ -port _db_port_] [-rman {-controlfile | {-login-username _rman_username_ -password _rman_password_ -tnsname _rman_tnsname_} } ] -osaccount _osaccount_ -osgroup _osgroup_ [-retain [-hourly-count _n_] [-duration _m_]] [-daily-count _n_] [-duration _m_]] [-weekly-count _n_] [-duration _m_]] [-monthly-count _n_] [-duration _m_]]] [-profile-comment _profile-comment_][-snapname-pattern _pattern_][-protect [-protection-policy _policy_name_]] | [-noprotect]][-summary-notification] [-notification [-success-email _email_address1, email_address2_ -subject _subject_pattern_] [-failure-email _email_address1, email_address2_ -subject _subject_pattern_]][-quiet | -verbose]-dump*`


