---
permalink: unix-administration/task-mount-backups.html 
sidebar: sidebar 
keywords: snapmanager, automatic, handle, mount, backup, available, host, scenario, external, tool, oracle, recovery, manager, rman, access, file 
summary: 'SnapManager gère automatiquement le montage d"une sauvegarde pour la rendre disponible à l"hôte. Vous pouvez également monter des sauvegardes dans les situations où vous utilisez un outil externe, comme Oracle Recovery Manager (RMAN), pour accéder aux fichiers de la sauvegarde.' 
---
= Montez les sauvegardes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager gère automatiquement le montage d'une sauvegarde pour la rendre disponible à l'hôte. Vous pouvez également monter des sauvegardes dans les situations où vous utilisez un outil externe, comme Oracle Recovery Manager (RMAN), pour accéder aux fichiers de la sauvegarde.

*À propos de cette tâche*

Le `smsap backup mount` Commande affiche la liste des chemins d'accès vers lesquels les copies Snapshot constituées de la sauvegarde ont été montées.

Vous pouvez utiliser le `-from-secondary` option permettant de monter la sauvegarde à partir du stockage secondaire. Si vous n'utilisez pas cette option, SnapManager monte la sauvegarde à partir du stockage principal.

Vous devez spécifier le `-copy-id` lorsque vous spécifiez le `-from-secondary` option. S'il y a plusieurs sauvegardes sur le système de stockage secondaire, le `-copy-id` permet de spécifier la copie de sauvegarde sur le stockage secondaire à utiliser pour monter la sauvegarde.6


NOTE: Si vous utilisez Data ONTAP sous 7-mode, vous devez indiquer une valeur valide pour le système `-copy-id` option. Cependant, si vous utilisez clustered Data ONTAP, le `-copy-id` cette option n'est pas requise.

Si vous montez une sauvegarde de base de données sur un hôte distant, vous devez vous assurer que les informations d'identification ASM (Automatic Storage Management) sont les mêmes sur les deux hôtes.


NOTE: Vous pouvez éventuellement collecter les fichiers de vidage après une opération de montage de sauvegarde réussie ou ayant échoué.

.Étape
. Pour monter une sauvegarde, entrez la commande suivante :
+
`*smsap backup mount -profile _profile_name label_ [data | -archivelogs] | -id _id_} [-host _-host_] [-from-secondary [-copy-id _id_]] [-dump] [-quiet | -verbose]*`


