---
permalink: unix-administration/task-schedule-backups-with-sap-transaction-db13.html 
sidebar: sidebar 
keywords: enable, backup, snapmanager, sap, dba, planning, calendar, transaction, db13, scheduling 
summary: 'Il existe plusieurs étapes requises pour permettre à SnapManager for SAP de travailler à partir de la transaction DB13 du calendrier de planification de l"administrateur de bases de données.' 
---
= Planifier des sauvegardes avec la transaction SAP DB13
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il existe plusieurs étapes requises pour permettre à SnapManager for SAP de travailler à partir de la transaction DB13 du calendrier de planification de l'administrateur de bases de données.

.Étapes
. Modifiez les autorisations de l' `/oracle/SID/sapbackup` répertoire permettant l'accès en écriture par l'identifiant utilisateur sidadm.
+
Utiliser la commande suivante comme `orasid`:

+
`*chmod 775 /oracle/SID/sapbackup*`

+
Cela permettra aux membres du `dba` groupe à écrire dans ce répertoire. L'identifiant utilisateur `sidadm` est membre du `dba` groupe.

. Modifiez les autorisations du fichier d'informations d'identification SnapManager pour SAP pour `orasid` pour autoriser `sidadm` l'accès. Utiliser la commande suivante exécutée par `orasid`:
+
Utiliser la commande suivante exécutée par `orasid`:

+
`*chmod 660 /oracle/SID/.netapp/smsap/credentials*`

+
Suivez les instructions de la section 3.3, « enregistrement des systèmes dans le référentiel » du document TR-3582 « meilleures pratiques de SnapManager pour SAP » pour enregistrer l'identifiant utilisateur sidadm dans le référentiel SnapManager pour SAP.


