---
permalink: unix-administration/task-clone-databases-and-using-custom-plugin-scripts.html 
sidebar: sidebar 
keywords: snapmanager, method, custom, script, clone, operation, occur, database, sid, policy, plug-in, cloning 
summary: 'SnapManager offre une méthode d"utilisation de vos scripts personnalisés avant et après une opération de clonage. Par exemple, vous avez peut-être créé un script personnalisé qui valide un SID de base de données clone et garantit que le SID est autorisé par votre stratégie de nommage. Le plug-in de clonage SnapManager vous permet d"inclure vos scripts personnalisés et de les exécuter automatiquement avant ou après une opération de clonage SnapManager.' 
---
= Clonez des bases de données et utilisez des scripts de plug-ins personnalisés
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager offre une méthode d'utilisation de vos scripts personnalisés avant et après une opération de clonage. Par exemple, vous avez peut-être créé un script personnalisé qui valide un SID de base de données clone et garantit que le SID est autorisé par votre stratégie de nommage. Le plug-in de clonage SnapManager vous permet d'inclure vos scripts personnalisés et de les exécuter automatiquement avant ou après une opération de clonage SnapManager.

.Étapes
. Afficher des exemples de scripts de plug-ins.
. Créez un script à partir de zéro ou modifiez l'un des exemples de scripts de plug-in.
+
Créez votre script personnalisé conformément aux instructions du script du plug-in SnapManager.

. Placez votre script personnalisé dans un emplacement de répertoire spécifié.
. Mettez à jour le fichier XML de spécifications de clone et incluez des informations sur votre script personnalisé qui doit être utilisé pendant le processus de clonage.
. Utilisez une commande SnapManager pour vérifier que les scripts personnalisés sont opérationnels.
. Lorsque vous lancez l'opération de clonage, incluez le nom du script et les paramètres facultatifs.

