---
permalink: unix-administration/task-view-detailed-clone-information.html 
sidebar: sidebar 
keywords: view, detail, information, clone, show, command 
summary: 'Vous pouvez afficher des informations détaillées sur un clone spécifique à l"aide de la commande clone show.' 
---
= Affiche des informations détaillées sur les clones
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez afficher des informations détaillées sur un clone spécifique à l'aide de `clone show` commande.

*À propos de cette tâche*

Le `clone show` la commande affiche les informations suivantes :

* Cloner l'identifiant système et l'ID de clone
* État de l'opération de clonage
* Créer une date ou une heure de début et de fin par le clone
* Cloner l'étiquette
* Commentaire sur le clone
* Etiquette et ID de sauvegarde
* Base de données source
* Sauvegarder les heures de début et de fin
* Nom de la base de données, espaces de stockage et fichiers de données
* Nom d'hôte et systèmes de fichiers contenant des fichiers de données
* Volumes du système de stockage et copies Snapshot qui sauvegardent le clone
* Indique si le clone a été créé à l'aide de la sauvegarde sur le stockage primaire ou secondaire


.Étape
. Saisissez la commande suivante :
+
`*smsap clone show -profile _profile_name_ [-label _label_ | -id _guid_]*`


