---
permalink: unix-administration/task-set-credentials-after-clearing-credential-cache.html 
sidebar: sidebar 
keywords: clear, cache, remove, store, user, credential, host, repository, repositories, profile, setting 
summary: 'Après avoir effacé le cache pour supprimer les informations d"identification de l"utilisateur stocké, vous pouvez définir les informations d"identification des hôtes, des référentiels et des profils.' 
---
= Définissez les informations d'identification après avoir effacé le cache des informations d'identification
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Après avoir effacé le cache pour supprimer les informations d'identification de l'utilisateur stocké, vous pouvez définir les informations d'identification des hôtes, des référentiels et des profils.

*À propos de cette tâche*

Vous devez vous assurer que vous définissez les mêmes informations d'identification utilisateur pour le référentiel, l'hôte de profil et le profil que vous avez donnés précédemment. Un fichier d'informations d'identification chiffré est créé lors de la configuration des informations d'identification de l'utilisateur.

Le fichier d'informations d'identification se trouve à `/root/.netapp/smsap/3.3.0`.

À partir de l'interface utilisateur graphique SnapManager, si aucun référentiel n'est placé sous des référentiels, effectuez les opérations suivantes :

.Étapes
. Cliquez sur *tâches* > *Ajouter un référentiel existant* pour ajouter un référentiel existant.
. Procédez comme suit pour définir les informations d'identification du référentiel :
+
.. Cliquez avec le bouton droit de la souris sur le référentiel et sélectionnez *Ouvrir*.
.. Dans la fenêtre *Repository Credentials Authentication*, saisissez les informations d'identification de l'utilisateur.


. Procédez comme suit pour définir les informations d'identification de l'hôte :
+
.. Cliquez avec le bouton droit de la souris sur l'hôte sous le référentiel et sélectionnez *Ouvrir*.
.. Dans la fenêtre *Host Credentials Authentication*, saisissez les informations d'identification de l'utilisateur.


. Procédez comme suit pour définir les informations d'identification du profil :
+
.. Cliquez avec le bouton droit de la souris sur le profil sous l'hôte et sélectionnez *Ouvrir*.
.. Dans la fenêtre *Profile Credentials Authentication* (authentification des informations d'identification du profil), saisissez les informations d'identification de l'utilisateur.



