---
permalink: unix-administration/task-clone-database-backups-without-resetlogs.html 
sidebar: sidebar 
keywords: snapmanager, enable, perform, flexible, cloning, clone, recover, database, manual, desire, point, resetlog, configure, data, guard, standby 
summary: 'SnapManager vous permet d"effectuer un clonage flexible afin de restaurer manuellement la base de données clonée à un point dans le temps sans avoir à ouvrir la base de données à l"aide de resetlogs. Vous pouvez également configurer manuellement la base de données clonée en tant que base de données de secours Data Guard.' 
---
= Cloner les sauvegardes de bases de données sans réinstaller les logs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager vous permet d'effectuer un clonage flexible afin de restaurer manuellement la base de données clonée à un point dans le temps sans avoir à ouvrir la base de données à l'aide de resetlogs. Vous pouvez également configurer manuellement la base de données clonée en tant que base de données de secours Data Guard.

*À propos de cette tâche*

Lorsque vous pouvez sélectionner le `-no-resetlogs` Option lors de la création du clone, SnapManager effectue les activités suivantes pour créer la base de données clonée :

. Exécute l'activité de tâche de prétraitement, si elle est spécifiée, avant de démarrer l'opération de clonage
. Crée la base de données clonée avec le SID spécifié par l'utilisateur
. Exécute les instructions SQL émises par la base de données clonée.
+
Seules les instructions SQL pouvant être exécutées à l'état de montage sont exécutées avec succès.

. Exécute l'activité de la tâche de post-traitement, si elle est spécifiée.


*Tâches à effectuer pour restaurer manuellement la base de données clonée*

. Montez les sauvegardes du journal d'archivage et restaurez manuellement la base de données clonée à l'aide des fichiers journaux d'archive du chemin monté.
. Après avoir effectué une restauration manuelle, ouvrez la base de données clonée récupérée à l'aide de `-resetlogs` option.
. Créez des espaces de stockage temporaires, le cas échéant.
. Exécutez l'utilitaire DBNEWID.
. Accordez le privilège sysdba aux informations d'identification de la base de données clonée.


Lors du clonage des sauvegardes de base de données à l'aide de `-no-resetlogs` En option, SnapManager laisse la base de données clonée à l'état monté pour la récupération manuelle.


NOTE: Base de données clonée créée avec la `-no-resetlogs` l'option n'est pas une base de données complète. Vous ne devez donc pas effectuer d'opérations SnapManager sur cette base de données, bien que SnapManager ne vous limite pas à effectuer d'opérations.

Si vous ne spécifiez pas le `-no-resetlogs` Option, SnapManager applique les fichiers journaux d'archive et ouvre la base de données avec réinitialismes.

.Étape
. Saisissez la commande suivante :
+
`*smsap clone create -profile _profile_name_ [-backup-label _backup_name_ | -backup-id _backup_id_ | current] -newsid _new_sid_ -clonespec _full_path_to_clonespecfile_ -no-resetlogs*`

+
Si vous essayez de spécifier les deux `-no-resetlogs` et `recover-from-location` Options, SnapManager ne vous permet pas de spécifier les deux options ensemble et affiche le message d'erreur : `SMSAP-04084: You must specify either one of the options: -no-resetlogs or -recover-from-location`.



'''


== Exemple

[listing]
----
smsap clone create -profile product -backup-label full_offline -newsid PROD_CLONE -clonespec prod_clonespec.xml -label prod_clone-reserve -no-reset-logs
----
'''