---
permalink: unix-administration/task-restore-backups-using-fast-restore.html 
sidebar: sidebar 
keywords: force, snapmanager, sap, volume-based, snaprestore, condition, restore, eligibility, restoring 
summary: 'Vous pouvez forcer SnapManager pour SAP à utiliser le processus SnapRestore basé sur les volumes plutôt que d"autres processus de restauration si toutes les conditions d"éligibilité à la restauration rapide sont remplies.' 
---
= Restaurez vos sauvegardes à l'aide de la fonction de restauration rapide
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez forcer SnapManager pour SAP à utiliser le processus SnapRestore basé sur les volumes plutôt que d'autres processus de restauration si toutes les conditions d'éligibilité à la restauration rapide sont remplies.

*À propos de cette tâche*

Vous pouvez utiliser la commande backup restore avec `-fast`:

`*backup restore -fast [require | override | fallback | off]*`

Vous pouvez utiliser le `-fast` option uniquement si vous souhaitez effectuer une restauration complète d'une sauvegarde complète. Le `-fast` l'option comprend les paramètres suivants :

* `require`: Vous permet d'effectuer une restauration de volume si toutes les conditions d'admissibilité de restauration obligatoires sont remplies et si aucune vérification de restauration excessive n'est trouvée.
+
Si vous spécifiez le `-fast` mais ne spécifiez aucun paramètre pour `-fast`, SnapManager utilise le `-require` paramètre par défaut.

* `override`: Vous permet de remplacer les vérifications d'éligibilité non obligatoires et d'effectuer la restauration rapide basée sur le volume.
* `fallback`: Permet de restaurer la base de données à l'aide de toute méthode que SnapManager détermine.
+
Si vous ne spécifiez pas `-fast`, SnapManager utilise le `-fallback` paramètre par défaut.

* `off`: Vous permet d'éviter le temps nécessaire pour effectuer toutes les vérifications d'admissibilité, pour effectuer un processus de restauration basé sur un fichier plutôt que le processus de restauration rapide.


Si la sauvegarde ne réussit pas les vérifications d'éligibilité obligatoires, la restauration rapide ne peut pas être effectuée correctement.

SnapManager effectue des restaurations rapides basées sur des volumes dans des environnements UNIX uniquement ; SnapManager n'effectue pas de restaurations rapides dans l'environnement Windows.

Lors de l'exécution de VBSR sur la sauvegarde du fichier de données, si les fichiers de données et les fichiers journaux d'archive sont présents dans le même volume et si les fichiers journaux d'archive ne sont pas présents dans le système de fichiers actif, la restauration et la récupération de la base de données ont réussi. Cependant, les snapshots futurs du journal d'archivage sont supprimés dans le cadre de VBSR, ce qui entraîne une entrée obsolète de la sauvegarde du journal d'archivage dans le référentiel.

.Étapes
. Saisissez la commande suivante :
+
`*smsap backup restore -profile _profile_name_ -label _label_ -complete-fast require-verbose*`

+
*Exemple*

+
[listing]
----
smsap backup restore -profile targetdb1_prof1
      -label full_bkup_sales_nov_08  -complete -fast require -verbose
----
. Vérifiez les vérifications d'éligibilité de restauration rapide.
. Si la vérification d'éligibilité détermine qu'aucune vérification obligatoire n'a échoué, si certaines conditions peuvent être remplacées et si vous souhaitez poursuivre le processus de restauration, entrez la commande suivante :
+
`*backup restore -fast override*`


