---
permalink: unix-administration/task-restore-backup-using-single-file-snaprestore.html 
sidebar: sidebar 
keywords: restore, backup, single, file, snaprestore, sfsr, method, restoring 
summary: 'Vous pouvez restaurer les sauvegardes à l"aide de la méthode SFSR (Single File SnapRestore).' 
---
= Restaurez les sauvegardes à l'aide de Single File SnapRestore
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez restaurer les sauvegardes à l'aide de la méthode SFSR (Single File SnapRestore).

.Étapes
. Créez un profil à partir de l'interface utilisateur graphique de SnapManager.
. Sauvegardez la base de données à l'aide de l'interface graphique.
. Dissocier les groupes de services Oracle et NFS (Network File System) des groupes de services du cluster et les figer.
. Assurez-vous que Secure Shell (SSH) est configuré entre les hôtes et SnapDrive pour UNIX par paramètre `_#secure-communication-among-cluster-nodes_` à `*on*` dans le `snapdrive.conf` fichier.
. À partir de l'interface graphique de SnapManager, effectuez des restaurations et des sauvegardes complètes à l'aide de `--alllogs`.
. Dégeler les groupes de services et les lier au groupe de services du cluster.
+

NOTE: Cette configuration ne s'applique que si vous utilisez SnapDrive 4.1.1 D2 pour UNIX et SnapDrive 4.2 pour UNIX.

+
Si une opération de restauration est suivie d'une autre opération de restauration, la création de la copie Snapshot de sauvegarde peut échouer. Si vous exécutez plusieurs opérations de restauration successives dans la durée spécifiée pendant laquelle la SFSR peut se terminer, SnapManager pour SAP risque de rencontrer des erreurs de création de copies Snapshot.

+
Pour éviter les erreurs de création de copies Snapshot, veillez à ce que les opérations de restauration soient effectuées après la période en cours de traitement SFSR.

+
Pour ce faire, vérifiez l'état du processus de fractionnement du clone de LUN en entrant la commande suivante à partir de l'interface de ligne de commandes du système de stockage :

+
`*rsh _filernname_ lun clone split status _lun-name_*`

+
[listing]
----

Sample Output:
/vol/delaware_760gb/lun700gb (64% complete)..
----
+

NOTE: La technologie SnapRestore basée sur les volumes (VBSR) n'est pas prise en charge sur les hôtes Solaris qui exécutent la pile Veritas avec l'environnement SFRAC et VCS.


