---
permalink: unix-administration/task-protect-archive-log-backups.html 
sidebar: sidebar 
keywords: create, creating, profile, enable, protection, archive, log, backup, policy, protect 
summary: 'Lors de la création de profils, vous pouvez activer la protection des sauvegardes des journaux d"archives en fonction de la stratégie de protection des journaux d"archives.' 
---
= Protéger les sauvegardes des journaux d'archivage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lors de la création de profils, vous pouvez activer la protection des sauvegardes des journaux d'archives en fonction de la stratégie de protection des journaux d'archives.

.Étape
. Saisissez la commande suivante :
+
`*smsap profile create -profile _profile_ [-profile-password _profile_password_] -repository -dbname _repo_dbname_ -host _repo_host_ -port _repo_port_ -login -username _repo_username_ -database -dbname _db_dbname_ -host _db_host_ [-sid _db_sid_] [-login-username _db_username_ -password _db_password_ -port _db_port_] [-rman {-controlfile | {-login-username _rman_username_ -password _rman_password_ -tnsname _rman_tnsname_} } ] -osaccount _osaccount_ -osgroup _osgroup_ [-retain [-hourly [-count _n_] [-duration _m_]] [-daily [-count _n_] [-duration _m_]] [-weekly [-count _n_] [-duration _m_]] [-monthly [-count _n_] [-duration _m_]]] [-comment _comment_][-snapname-pattern _pattern_][-protect [-protection-policy _policy_name_]] [-summary-notification] [-notification [-success-email _email_address1, email_address2_ -subject _subject_pattern_] [-failure-email _email_address1, email_address2_ -subject _subject_pattern_]][-separate-archivelog-backups-retain-archivelog-backups-hours _hours_ | -days _days_ | -weeks _weeks_ | -months _months_ [-protect [-protection-policy _policy_name_] | -noprotect] [-include-with-online-backups | -no-include-with-online-backups]] [-dump]*`

+
[cols="2a,5a"]
|===
| Si... | Alors... 


 a| 
*Vous voulez sauvegarder séparément les sauvegardes des journaux d'archive et protéger les fichiers journaux d'archive*
 a| 
Spécifiez les options suivantes :

** `-separate-archivelog-backups` permet de séparer les fichiers journaux d'archives des fichiers de données.
** `-protect` attribue une stratégie de protection distincte pour les sauvegardes du journal d'archivage.
** `-protection-policy` attribue la stratégie de protection pour les sauvegardes du journal d'archivage.


|===

