---
permalink: unix-installation-cmode/task-verify-the-oracle-listener-configuration.html 
sidebar: sidebar 
keywords: listener, process, listen, client, connection, request, receive, income, connection, request, traffic, database, target, repository, status, command, configuration, verify, oracle 
summary: 'L"écouteur est un processus qui écoute les demandes de connexion client. Il reçoit les demandes de connexion client entrantes et gère le trafic de ces requêtes vers la base de données. Avant de vous connecter à une base de données cible ou à une instance de base de données de référentiel, vous pouvez utiliser la commande STATUS pour vérifier la configuration de l"écouteur.' 
---
= Vérifiez la configuration de l'écouteur Oracle
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'écouteur est un processus qui écoute les demandes de connexion client. Il reçoit les demandes de connexion client entrantes et gère le trafic de ces requêtes vers la base de données. Avant de vous connecter à une base de données cible ou une instance de base de données de référentiel, vous pouvez utiliser le `STATUS` commande pour vérifier la configuration de l'écouteur.



== Description de la tâche

Le `STATUS` commande affiche des informations d'état de base sur un écouteur spécifique, y compris un résumé des paramètres de configuration de l'écouteur, des adresses de protocole d'écoute et un résumé des services enregistrés avec cet écouteur.

.Étape
. Entrez la commande suivante à l'invite de commande : `*lsnrctl STATUS*`
+
La valeur par défaut attribuée au port d'écoute est 1521.


