---
permalink: unix-installation-cmode/task-smsap-isg-schedule-recurring-backups.html 
sidebar: sidebar 
keywords: 'schedule, operation, backup, initiate, automatic, regular, interval, snapmanager, hourly, daily, weekly, monthly, one-time, basis, scheduling, recur summary: You can schedule backup operations so that the backups are initiated automatically at regular intervals. SnapManager allows you to schedule backups on an hourly, daily, weekly, monthly, or one-time basis.' 
---
= Planifiez des sauvegardes récurrentes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez planifier des opérations de sauvegarde de manière à ce que les sauvegardes soient lancées automatiquement à intervalles réguliers. SnapManager vous permet de planifier des sauvegardes toutes les heures, tous les jours, toutes les semaines, tous les mois ou à la fois.



== Description de la tâche

Vous pouvez attribuer plusieurs planifications de sauvegarde pour une même base de données. Toutefois, lorsque vous planifiez plusieurs sauvegardes pour la même base de données, vous devez vous assurer que les sauvegardes ne sont pas planifiées en même temps.

Ces étapes montrent comment créer un programme de sauvegarde pour votre base de données à l'aide de l'interface utilisateur SnapManager. Si vous préférez, vous pouvez également utiliser l'interface de ligne de commandes. Pour plus d'informations sur la planification des sauvegardes à l'aide de la CLI, reportez-vous au _SnapManager for SAP Administration Guide for UNIX_.

.Étapes
. Dans l'arborescence des référentiels, cliquez avec le bouton droit de la souris sur le profil contenant la base de données pour laquelle vous souhaitez créer un programme de sauvegarde, puis sélectionnez *Programmer la sauvegarde*.
. Dans *Label*, entrez un nom personnalisé pour la sauvegarde.
+
Vous ne devez pas inclure d'espaces ou de caractères spéciaux dans le nom. Si vous ne spécifiez pas de nom, SnapManager crée automatiquement une étiquette de sauvegarde.

+
À partir de SnapManager 3.4, vous pouvez modifier l'étiquette de sauvegarde créée automatiquement par SnapManager. Vous pouvez modifier le `override.default.backup.pattern` et `new.default.backup.pattern` variables de configuration pour créer votre propre modèle de libellé de sauvegarde par défaut.

. Facultatif : dans *étiquette SnapVault*, vous devez entrer l'étiquette SnapMirror que vous avez spécifiée dans les règles de la règle SnapMirror lors de la configuration de la relation SnapVault.
+

NOTE: Le champ *étiquette SnapVault* apparaît uniquement si vous avez sélectionné _SnapManager_cdot_Vault_ comme stratégie de protection lors de la création du profil.

. Sélectionnez *Autoriser le démarrage ou l'arrêt de la base de données, si nécessaire*, pour modifier l'état de la base de données, si nécessaire.
+
Cette option garantit que si la base de données n'est pas à l'état requis pour créer une sauvegarde, SnapManager place automatiquement la base de données à l'état souhaité pour terminer l'opération.

. Sur la page *Database*, *tablespaces* ou *fichiers de données* à *Backup*, effectuez les opérations suivantes :
+
.. Sélectionnez *Sauvegarder les fichiers de données* pour sauvegarder la base de données complète, les fichiers de données sélectionnés ou les espaces de stockage sélectionnés.
.. Sélectionnez *Backup Archivelugs* pour sauvegarder les fichiers journaux d'archive séparément.
.. Sélectionnez *Prune Archivelugs* si vous souhaitez supprimer les fichiers journaux d'archives du système de fichiers actif qui est déjà sauvegardé.
+

NOTE: Si la zone de récupération Flash (FRA) est activée pour les fichiers journaux d'archive, SnapManager ne parvient pas à nettoyer les fichiers journaux d'archive.

.. Sélectionnez *protéger la sauvegarde* si vous souhaitez activer la protection de sauvegarde.
+
Cette option n'est activée que si la stratégie de protection a été sélectionnée lors de la création du profil.

.. Dans la liste déroulante *Type*, sélectionnez le type de sauvegarde (hors ligne ou en ligne) que vous souhaitez créer.
+
Si vous sélectionnez _Auto_, SnapManager crée une sauvegarde basée sur l'état actuel de la base de données.

.. Dans la liste déroulante *classe de rétention*, sélectionnez la classe de rétention.
.. Cochez la case *vérifier la sauvegarde à l'aide de l'utilitaire Oracle DBVERIFY* si vous souhaitez vous assurer que les fichiers sauvegardés ne sont pas corrompus.


. Dans le champ *Nom de l'horaire*, saisissez un nom personnalisé de l'horaire.
+
Vous ne devez pas inclure d'espaces dans le nom.

. Sur la page *configurer le programme de sauvegarde*, effectuez les opérations suivantes :
+
.. Dans la liste déroulante * effectuer cette opération*, sélectionnez la fréquence de la planification de sauvegarde.
.. Dans le champ *Date de début*, indiquez la date à laquelle vous souhaitez lancer la planification de sauvegarde.
.. Dans le champ *Start Time*, indiquez l'heure à laquelle vous souhaitez lancer la planification de sauvegarde.
.. Spécifiez l'intervalle de création des sauvegardes.
+
Par exemple, si vous avez sélectionné la fréquence horaire et que vous spécifiez l'intervalle comme 2, les sauvegardes seront planifiées toutes les 2 heures.



. Sur la page *activation tâche*, indiquez si vous souhaitez effectuer des tâches avant et après la fin des opérations de sauvegarde.
. Sur la page *effectuer une opération de planification de sauvegarde*, vérifiez les informations et cliquez sur *planifier*.
. Cliquez sur *Terminer* pour fermer l'assistant.
+
Si l'opération échoue, cliquez sur *Détails de l'opération* pour voir ce qui a provoqué l'échec de l'opération.



*Informations connexes*

https://library.netapp.com/ecm/ecm_download_file/ECMP12481453["Guide d'administration SnapManager 3.4.1 pour SAP pour UNIX"^]
