---
permalink: unix-installation-7mode/reference-trademark.html 
sidebar: sidebar 
keywords: trademark, information 
summary: Informations sur les marques commerciales 
---
= Informations sur les marques commerciales
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


Active IQ, AltaVault, Arch Design, ASUP, AutoSupport, Campaign Express, Clustered Data ONTAP, Customer Fitness, Data ONTAP, DataMotion, Element, Fitness, Flash Accel, Flash Cache, Flash Pool, FlexCache, FlexClone, FlexPod, FlexScale, FlexShare, FlexVol, FPolicy, Fueled by SolidFire, GetSuccessful, Helix Design, LockVault, Manage ONTAP, MetroCluster, MultiStore, NetApp, NetApp Insight, OnCommand, ONTAP, ONTAPI, RAID DP, RAID-TEC, SANscreen, SANshare, SANtricity, SecureShare, Simplicity, Simulate ONTAP, Snap Creator, SnapCenter, SnapCopy, SnapDrive, SnapIntegrator, SnapLock, SnapManager, SnapMirror, SnapMover, SnapProtect, SnapRestore Snapshot, SnapValidator, SnapVault, SolidFire, SolidFire Helix, StorageGRID, SyncMirror, Tech OnTap, Unbound Cloud et WAFL , ainsi que d'autres noms, sont des marques commerciales ou des marques déposées de NetApp, Inc. aux États-Unis et/ou dans d'autres pays. Toutes les autres marques ou produits sont des marques commerciales ou des marques déposées de leurs détenteurs respectifs et doivent être traités comme tels. Une liste actuelle des marques déposées NetApp est disponible sur le Web.

http://www.netapp.com/us/legal/netapptmlist.aspx[]
