---
permalink: unix-installation-7mode/task-update-the-existing-repository.html 
sidebar: sidebar 
keywords: update, exist, repository, upgrading, upgrade, updating, snapmanager, path 
summary: 'Vous n"avez pas besoin de mettre à jour le référentiel existant si vous effectuez une mise à niveau de SnapManager 3.3.x vers SnapManager 3.4 ou version ultérieure, mais pour tous les autres chemins de mise à niveau, vous devez mettre à jour le référentiel existant pour pouvoir y accéder après la mise à niveau.' 
---
= Mettre à jour le référentiel existant
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous n'avez pas besoin de mettre à jour le référentiel existant si vous effectuez une mise à niveau de SnapManager 3.3.x vers SnapManager 3.4 ou version ultérieure, mais pour tous les autres chemins de mise à niveau, vous devez mettre à jour le référentiel existant pour pouvoir y accéder après la mise à niveau.

*Ce dont vous aurez besoin*

* Le serveur SnapManager mis à niveau doit avoir été démarré et vérifié.
* Une sauvegarde du référentiel existant doit exister.


*À propos de cette tâche*

* Si vous mettez à niveau une version antérieure à SnapManager 3.1 vers SnapManager 3.3 ou une version ultérieure, vous devez d'abord effectuer une mise à niveau vers SnapManager 3.2.
+
Après la mise à niveau vers SnapManager 3.2, vous pouvez ensuite effectuer une mise à niveau vers SnapManager 3.3 ou version ultérieure.

* Après la mise à jour du référentiel, vous ne pouvez pas utiliser le référentiel avec une version antérieure de SnapManager.


.Étape
. Mettre à jour le référentiel existant :
+
`*smsap repository update -repository -dbname repository_service_name -host repository_host_name -login -username repository_user_name -port repository_port*`

+
** Le nom d'utilisateur du référentiel, le nom du service de référentiel et le nom d'hôte du référentiel peuvent comprendre des caractères alphanumériques, un signe moins, un trait de soulignement et un point.
** Le port du référentiel peut être n'importe quel numéro de port valide. Les autres options utilisées lors de la mise à jour du référentiel existant sont les suivantes :
** Le `force` option
** Le `noprompt` option
** Le `quiet` option
** Le `verbose` option
+
*Exemple*

+
[listing]
----
smsap repository update -repository -dbname HR1
-host server1 -login -username admin -port 1521
----




*Après la fin*

Redémarrez le serveur SnapManager pour redémarrer les plannings associés.
